jakartaee/data

api/src/main/java/jakarta/data/repository/Repository.java
=> fix HTML5 errors in JavaDoc

api/src/main/java/jakarta/data/repository/OrderBy.java, api/src/main/java/jakarta/data/repository/Repository.java, spec/src/main/asciidoc/repository.asciidoc
=> OrderBy annotation for sorting

api/src/main/java/jakarta/data/repository/CrudRepository.java, api/src/main/java/jakarta/data/repository/Limit.java, api/src/main/java/jakarta/data/repository/OrderBy.java, api/src/main/java/jakarta/data/repository/Repository.java
fixes #23
I'm planning to add an additional commit to this after #27 goes in to update repository.asciidoc, but didn't update it yet to avoid merge conflicts with that pull.
=> Limit and findFirst...By

api/src/main/java/jakarta/data/repository/PageableRepository.java
This PR updates the PageableRepository interface to extend from the CrudRepository interface as outlined in the diagram.
=> Update PageableRepository<T, K> to extend from CrudRepository<T, K>

api/src/main/java/jakarta/data/repository/Pageable.java, api/src/main/java/jakarta/data/repository/Repository.java, api/src/test/java/jakarta/data/repository/PageableTest.java
Fixes #41 along with 2 minor JavaDoc typos that I noticed while making the updates.
=> Pageable.size and fix 2 javadoc typos

spec/src/main/asciidoc/jakarta-data.asciidoc
This PR is contingent upon PR #47 in which the Jakarta EE logo was added.
=> Add reference to Jakarta EE logo in jakarta-data.asciidoc file

README.adoc
This PR aims to add more information and explain more details in the README file.
- Update README file
=> Improve readme with more project information

api/src/main/java/jakarta/data/repository/KeysetAwarePage.java, api/src/main/java/jakarta/data/repository/KeysetAwareSlice.java, api/src/main/java/jakarta/data/repository/KeysetPageable.java, api/src/main/java/jakarta/data/repository/OrderBy.java, api/src/main/java/jakarta/data/repository/Pageable.java, api/src/main/java/jakarta/data/repository/Sort.java, api/src/test/java/jakarta/data/repository/KeysetPageableTest.java, api/src/test/java/jakarta/data/repository/PageableTest.java, spec/src/main/asciidoc/repository.asciidoc
Keyset pagination API and JavaDoc for #39
=> keyset pagination API and JavaDoc

api/src/main/java/jakarta/data/repository/Direction.java, api/src/main/java/jakarta/data/repository/KeysetPageable.java, api/src/main/java/jakarta/data/repository/OrderBy.java, api/src/main/java/jakarta/data/repository/Pageable.java, api/src/test/java/jakarta/data/repository/KeysetPageableTest.java, api/src/test/java/jakarta/data/repository/PageableTest.java
* Remove colon at enum
* Remove [redudant public](https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.1)
=> Remove unnecessary indicator

.github/ISSUE_TEMPLATE/tck-challenge.yml
=> Issue template for TCK Challenges

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
It is not the perfect solution, but it is a good MVP.
We have an issue to solve this on this issue: https://github.com/jakartaee/data/issues/104
Signed-off-by: Otavio Santana <otaviopolianasantana@gmail.com>
=> Return version to SNAPSHOT

CHANGELOG.adoc, api/pom.xml, pom.xml, spec/pom.xml, tck-dist/pom.xml, tck/pom.xml
As we discussed on the e-mail list:  https://www.eclipse.org/lists/data-dev/msg00081.html
* As a first step, we'll create a second Beta version.
After the next meeting, we'll discuss the following:
* Discuss the plan view to submit to the Jakarta EE committee
* Discuss the TCK and documentation
=> Update the beta version to release second beta of Jakarta-Data

tck/src/main/java/ee/jakarta/tck/data/core/entity/EntityTest.java, tck/src/main/java/ee/jakarta/tck/data/core/entity/Student.java, tck/src/main/java/ee/jakarta/tck/data/core/entity/StudentDirectory.java, tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/EntityProvider.java
=> Example of dual annotaions

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbersPopulator.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
5 TCK test scenarios from #133 covering basic usage of `Slice`.
=> basic TCK tests for Slice

api/src/main/java/jakarta/data/repository/Repository.java
=> clarifications on inject and other entity models

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
Add TCK tests for precedence scenarios with Sort.
Add TCK tests for Limit.
=> Tests for Sort/OrderBy precedence and Limit

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharactersPopulator.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
Add tests for these scenarios from #133
- Use a repository that inherits from DataRepository and defines all of its own methods.
- Use a repository method that returns Streamable and verify the results.
- Use a repository method that returns a single entity value where a single result is found.
- Use a repository method that returns a single entity value where no result is found. Expect EmptyResultException.
- Use a repository method that ought to return a single entity value but where multiple results are found. Expect NonUniqueResultException.
=> Tests for DataRepository, Streamable, and single entity result

README.adoc
* Include links in the README file
* Remove unnecessary extra lines.
* Update the maven version with the lastest Jakarta API version.
=> Enhance README file

CHANGELOG.adoc, spec/src/main/asciidoc/jakarta-ee.adoc
- Modify CDI support CDI full and Lite
- Include a sample of Jakarta NoSQL
- Include a sample of Jakarta Data
- Explore Jakarta Validation
=> Enhances Jakarta EE Data documentation

CHANGELOG.adoc, api/pom.xml, pom.xml, spec/pom.xml, tck-dist/pom.xml, tck/pom.xml
=> Release 1.0.0 b3

README.adoc
I noticed the smallest possible typo while reading the readme of the repo. Here's my contribution to the world of data access :)
=> Fix small typo: dara -> data

CHANGELOG.adoc, spec/src/main/asciidoc/repository.asciidoc
Enhanced Documentation: Explanation of Jakarta Data Extension Features
This Pull Request addresses the documentation enhancement regarding Jakarta Data's extension features for Java persistence. The changes provide a more comprehensive understanding of the features and their benefits to Java developers. Additionally, the modifications include examples and explanations of how these extension features can streamline code design and promote code reusability.
- Added an introduction section providing context on the extension features.
- Expanded explanations for Default Methods, Interface Queries, and Custom Repositories.
- Highlighted the ability to combine Default Methods with Interface Queries for enhanced functionality.
- Included examples of code snippets illustrating each feature.
- …
=> Enhanced Documentation: Explanation of Jakarta Data Extension Features

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
TCK tests for #133 that cover using the Query annotation to supply JPQL with positional parameters and named parameters.
=> Tests for query annotation with JPQL

api/src/main/java/jakarta/data/repository/CrudRepository.java
- enhances the save method at CrudRepository
I made some suggestions to enhance and put more details into the save method. I agree with [Oliver's comments](https://github.com/jakartaee/data/issues/229#issuecomment-1701248061) I could see several points on JPA I will create a JPA specialization where we can put those points in another PR.
It solves a part of: https://github.com/jakartaee/data/issues/229
=> Enhances the save method at CrudRepository

spec/src/main/asciidoc/repository.asciidoc
Changes: 
Fix: https://github.com/jakartaee/data/issues/236
=> Fix Consider formalizing the Query by Method section

spec/src/main/asciidoc/repository.asciidoc
- Include the BNF session at query by method.
Solve the second part of: https://github.com/jakartaee/data/issues/236
=> Incluse the BNF to query method

spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc, spec/src/main/asciidoc/repository.asciidoc
- Make the specification more self-contained.
Fixes: https://github.com/jakartaee/data/issues/222
=> explain the goals of Jakarta Data and motivate/justify/explain the selected design [Part 2]

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
Add a TCK test for obtaining the EntityManager from a repository method.
=> TCK test for EntityManager method

spec/src/main/asciidoc/repository.asciidoc
It is the first part of the solution to: https://github.com/jakartaee/data/issues/255
=> Query by method name and Query by parameters

spec/src/main/asciidoc/jakarta-ee.adoc
Git diff was doing a poor job of matching up what changed, making it look like more changed than really did, so I tried splitting the changes into separate commits.  It might help to look at those individually when reviewing.
Fixes #278
=> Corrections to requirements around CDI extensions

api/src/main/java/module-info.java
Update the JavaDoc to match up with the specification updates that are being made under 273 and include the life cycle methods
=> Align JavaDoc with spec updates from 273

tck/pom.xml, tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
For #267
Wait to do the final signature file update until all changes to API signatures updates are finalized for milestone 1 release.
This PR is a placeholder for that work.
=> Update signature files and signature generation

api/src/main/java/jakarta/data/metamodel/Attribute.java, api/src/main/java/jakarta/data/metamodel/AttributeInfo.java, api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/metamodel/package-info.java, api/src/main/java/module-info.java, tck/pom.xml, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiChar_.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacter_.java, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/sig-test-pkg-list.txt
- Rename Package to follow the same name as Jakarta Persistence
=> Update package name to metamodel to follow the Jakarta Persistence

CHANGELOG.adoc, README.adoc
- Update changelog
- Update readme
=> update documentation at readme and changelog

tck-dist/pom.xml
=> Fix jruby dependency

api/src/main/java/jakarta/data/page/KeysetAwareSlice.java, api/src/main/java/jakarta/data/page/package-info.java, api/src/main/java/jakarta/data/repository/Repository.java
- Fix a typo
- Fix the class links at the Javadoc.
=> Small fixes while review Javadoc

spec/src/main/asciidoc/repository.asciidoc
=> Small fixes at the spec side

spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc
Proofreading of introduction.asciidoc which covers the introduction (1.0), goals (1.1), and non-goals (1.2).
=> review of introduction and goals section

spec/src/main/asciidoc/repository.asciidoc
Proofread section 4.8: Pagination
I also added a list of requirements for offset pagination, and added a few missing requirements to the corresponding list for keyset cursor pagination.
=> proofread section 4.8: pagination

CHANGELOG.adoc, README.adoc, api/pom.xml, tck-dist/pom.xml, tck-dist/src/main/starter/ee-pom.xml, tck-dist/src/main/starter/se-pom.xml, tck/pom.xml
Fixes: 
https://github.com/jakartaee/data/issues/361
=> Update jakarta ee convention

spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc, spec/src/main/asciidoc/repository.asciidoc
Read over the spec at a high level and identify some of the more obvious places where it could be more concise.  This is being done for #353
=> preliminary review for conciseness

.github/workflows/release.yml
=> Typo in release workflow

api/src/main/java/jakarta/data/repository/BasicRepository.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbersPopulator.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Changes:
- https://github.com/jakartaee/data/issues/412
=> [Fix]Should non-standard query by methods be supported by user defined repositories

.github/workflows/ci.yml, tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc, tck-dist/src/main/starter/ee-pom.xml, tck-dist/src/main/starter/se-pom.xml, tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
=> TCK allow certification against Java 17 and 21

.github/workflows/update.yml, CHANGELOG.adoc, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
=> Update signature files 1.0.0-M3

api/src/main/java/jakarta/data/Sort.java, api/src/main/java/module-info.java, api/src/test/java/jakarta/data/page/PageableTest.java
This fixes a couple of typos that I noticed while investigating another issue.
=> Fix various typos

CHANGELOG.adoc, api/src/main/java/jakarta/data/repository/Find.java, spec/src/main/asciidoc/repository.asciidoc
Include
```java
interface Garage {
@Find
List<Car> getCarWithModel(@By("model") String model);
}
```
=> Include find annotation

api/src/main/java/jakarta/data/page/Slice.java, api/src/main/java/jakarta/data/repository/BasicRepository.java, api/src/main/java/jakarta/data/repository/By.java, api/src/main/java/jakarta/data/repository/Delete.java, api/src/main/java/jakarta/data/repository/Insert.java, api/src/main/java/jakarta/data/repository/PageableRepository.java, api/src/main/java/jakarta/data/repository/Save.java, api/src/main/java/jakarta/data/repository/Update.java, api/src/main/java/module-info.java, spec/src/main/asciidoc/repository.asciidoc, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
This pull updates tests in the TCK to use the new `Find` annotation, and also updates a few other places that were missed.
=> Update the TCK and other missed places for the Find annotation

spec/src/main/asciidoc/repository.asciidoc
=> definition of entity inheritance

spec/src/main/asciidoc/jakarta-ee.adoc
Folks I would like to propose a bit of a rework of chapter 5.
WDYT? 
@njr-11 I believe you wrote the current version. Do you think this is an improvement? Does it miss anything important?
=> rework section on provider/repository

spec/src/main/asciidoc/jakarta-data.adoc, spec/src/theme/jakartaee-theme.yml
I originally made this for the JPA spec. Try it out by just building the PDF.
=> add PDF theme

README.adoc
=> Enhance readme file explain more about the type safe

spec/src/main/asciidoc/jakarta-ee.adoc
I'm trying to make very clear who is responsible for what, and which things are prescriptive requirements on the implementation of Jakarta Data, vs just being information about how Jakarta Data can take advantage of CDI/JTA/Interceptors.
=> expand spec sections on JTA and Jakarta Interceptors

spec/src/main/asciidoc/repository.asciidoc
It is pretty similar to the https://github.com/jakartaee/data/pull/497 for getting consistency
If we say that it is a safer approach, the majority of the sample in the spec should follow it.
=> Update using generic

api/src/main/java/jakarta/data/page/impl/SliceRecord.java
This is a small fix to #491.
I was just in the process of force pushing this when @otaviojava merged #491.
Anyway, this should be merged.
=> fix to SliceRecord

api/src/main/java/jakarta/data/Limit.java, api/src/main/java/jakarta/data/Sort.java, api/src/main/java/jakarta/data/exceptions/NonUniqueResultException.java, api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/page/PageRequest.java, api/src/main/java/jakarta/data/page/package-info.java, api/src/main/java/jakarta/data/repository/BasicRepository.java, api/src/main/java/jakarta/data/repository/CrudRepository.java, api/src/main/java/module-info.java
including some fixes to out of date info in module-info.java
see #519
=> lots of improvements to the Javadoc

api/src/main/java/jakarta/data/Limit.java, api/src/main/java/jakarta/data/Order.java, api/src/main/java/jakarta/data/Sort.java, api/src/main/java/jakarta/data/page/PageRequest.java, spec/src/main/asciidoc/repository.asciidoc
=> fix up spec and javadoc requirements with respect to special parameters

api/src/main/java/jakarta/data/Sort.java
=> recover javadoc change which was lost during merge

api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/repository/BasicRepository.java, api/src/main/java/jakarta/data/repository/By.java, api/src/main/java/jakarta/data/repository/CrudRepository.java, api/src/main/java/jakarta/data/repository/DataRepository.java, api/src/main/java/jakarta/data/repository/Delete.java, api/src/main/java/jakarta/data/repository/Find.java, api/src/main/java/jakarta/data/repository/Query.java, api/src/main/java/module-info.java, spec/src/main/asciidoc/repository.asciidoc
For #458.
In readiness for the integration of JDQL, we need to clean up this section which focussed on Query by Method Name, and said some things which were ambiguous or not quite right as applied to `@Query` and `@Find`.
=> alignment of @Find and @Delete with JDQL work

spec/src/main/asciidoc/query-language.asciidoc
Two small things that should be said explicitly.
=> two clarifications to semantics of 'order by'

api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
Ref: https://github.com/jakartaee/data/issues/559
=> Small fix at genetic staticmetamodel

api/src/main/java/jakarta/data/repository/BasicRepository.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
- Remove exists, findIn, deleteIn methods at BasicRepository
=> Remove methods at BasicRepository

api/src/main/java/module-info.java
- some topics were very inadequately covered, considering their importance in Jakarta Data
- the organization of the material was quite confusing
- there was some outdated info
=> clean up and reorg module-info.java

.github/ISSUE_TEMPLATE/release.yml, pom.xml, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
- Update signatures
- Update Jakarta EE dependencies to Jakarta EE 11 versions
=> Update for Milestone 4

spec/src/main/asciidoc/repository.asciidoc
- fix a typo
- be more explicit
=> improve two sentences of spec

tck/pom.xml
- Upgrade Jakarta NoSQL API version.
=> Upgrade Jakarta NoSQL API version

spec/src/main/asciidoc/jakarta-ee.adoc
=> fix section in interceptor bindings

spec/src/main/asciidoc/repository.asciidoc
I missed some of these earlier, as @otaviojava pointed out on the previous PR #590.
=> formatting of pagination-related code examples

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
1. change Iterable -> List in TCK to comply with recent change to the spec
2. remove requirement that repo be backed by `EntityManager`, which was never required
=> change Iterable -> List in TCK & remove requirement that repo be backed by EntityManager

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
we removed the `Contains` and `Empty` operators from query by method name
=> remove TCK test for removed features of query by method name

api/src/main/java/jakarta/data/Order.java, api/src/main/java/jakarta/data/Sort.java
Reading more carefully, I saw there was more to do.
=> more work on javadoc for Order and Sort

api/src/main/java/jakarta/data/Order.java, api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/page/CursoredPage.java, api/src/main/java/jakarta/data/page/Page.java, api/src/main/java/jakarta/data/repository/OrderBy.java, api/src/main/java/jakarta/data/repository/Param.java, api/src/main/java/jakarta/data/repository/Query.java, api/src/main/java/module-info.java
- fallout from removal of type variable from `PageRequest`
- removal of some uses of `{@code }` inside `<pre>`, which renders  extremely weirdly in IntelliJ
- improve description of ordering in `@OrderBy`
=> fixes to Javadoc

spec/src/main/asciidoc/repository.asciidoc
=> fix another broken link

api/src/main/java/jakarta/data/Sort.java, api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/metamodel/package-info.java, api/src/main/java/jakarta/data/page/CursoredPage.java, api/src/main/java/jakarta/data/repository/BasicRepository.java, api/src/main/java/jakarta/data/repository/By.java, api/src/main/java/jakarta/data/repository/CrudRepository.java, api/src/main/java/jakarta/data/repository/DataRepository.java, api/src/main/java/jakarta/data/repository/Delete.java, api/src/main/java/jakarta/data/repository/Find.java, api/src/main/java/jakarta/data/repository/Insert.java, api/src/main/java/jakarta/data/repository/Save.java, api/src/main/java/jakarta/data/repository/Update.java, api/src/main/java/module-info.java
=> fix  {@code } inside <pre>

pom.xml
=> Add issue management to pom.xml

spec/src/main/asciidoc/method-query.asciidoc
=> improve presentation of info on Query by Method Name

tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc, tck-dist/src/main/asciidoc/sections/04prereq.adoc, tck-dist/src/main/starter/ee-pom.xml, tck-dist/src/main/starter/se-pom.xml, tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md
I think but am not certain that this is needed.
=> update sigtest to 2.2 everywhere

api/src/main/java/jakarta/data/page/PageRequest.java
Very minor correction to wording that I spotted while reviewing JavaDoc.
=> Missing word in PageRequest javadoc

api/src/main/java/jakarta/data/Limit.java
=> fix missed {@code } in <pre>

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
=> Revert "TCK test for ID(THIS)"

api/pom.xml, pom.xml, spec/pom.xml, tck-dist/pom.xml, tck/pom.xml
=> Prepare for service release 1.0.1

.github/workflows/ci.yml
Need to backport this change to RELEASE-1.0.0
=> Ensure pulls and merges to RELEASE-1.0.0 run CI build

.github/workflows/ci.yml
This will be picked up by all future service release branches.
=> Ensure future pulls and merges to service branches run CI build

.github/workflows/ci.yml, pom.xml, tck-dist/src/main/pom.xml, tck-dist/src/main/starter/ee-pom.xml, tck-dist/src/main/starter/se-pom.xml
=> Update Arquillian BOM

README.adoc
Updated README to conform to maven best practices :)
=> README.adoc - maven best practices

tck-dist/src/main/asciidoc/data-tck-reference-guide.html, tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/NoSQLEntityTests.java
- Remove exception when the field is not mapped
Once the Jakarta NoSQL allows the Jakarta NoSQL vendor to allow mapping without annotation, this validation does not make sense.
=> Remove validation at find non-annotated field at NoSQL side

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Alternative to #805 that more precisely excludes the arithmetic updates behavior that NoSQL databases might not be capable of.
=> TCK cannot expect NoSQL to be capable of arithmetic in updates

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Fix a TCK when we have not change at the testUpdateQueryWithWhereClause method.
=> Update c1xExpected at the testUpdateQueryWithWhereClause method

api/pom.xml, api/src/main/resources/rules.xml
=> fix: remove AbstractClassWithoutAbstractMethod check

api/src/main/java/jakarta/data/page/PageRequest.java
This is a copy of the original PR from a contributor who wasn't interested in completing the Eclipse Foundation committer agreement.
=> Update PageRequest.java to fix minor JavaDoc issues

api/src/main/java/jakarta/data/metamodel/BasicAttribute.java, api/src/main/java/jakarta/data/metamodel/ComparableAttribute.java, api/src/main/java/jakarta/data/metamodel/SortableAttribute.java, api/src/main/java/jakarta/data/metamodel/TextAttribute.java, api/src/main/java/jakarta/data/metamodel/impl/BasicAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/ComparableAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/restrict/Restrict.java, api/src/test/java/jakarta/data/metamodel/AttributeTest.java, api/src/test/java/jakarta/data/metamodel/SortableAttributeTest.java
See explanation here: https://github.com/jakartaee/data/issues/829#issuecomment-2654769536
=> introduce BasicAttribute, ComparableAttribute to make restrictions typesafe

spec/src/main/asciidoc/repository.asciidoc
See #19 and #17.
Looking for feedback here!
=> initial proposal for reactive/async repositories

api/src/main/java/jakarta/data/repository/Query.java, spec/src/antlr/JDQL.g4, spec/src/main/asciidoc/query-language.asciidoc
Starting point for discussion. This is probably not quite right as written.
=> minimal possible change to allow multiple-element select lists

api/src/main/resources/checkstyle.xml, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
TCK tests for scenarios where:
- JDQL query returns Java record type that has the Select annotation on record components
- JDQL query returns Java record type where the record components determine the entity attributes retrieved
- JDQL query with a SELECT of multiple entity attributes returns Java record type
=> TCK tests for Query methods returning Java record

spec/src/main/asciidoc/repository.asciidoc
=> add section about null arguments to spec

api/src/main/java/module-info.java
=> javadoc fixes to module descriptor

api/src/main/java/jakarta/data/metamodel/Attribute.java, api/src/main/java/jakarta/data/metamodel/BasicAttribute.java, api/src/main/java/jakarta/data/metamodel/ComparableAttribute.java, api/src/main/java/jakarta/data/metamodel/NavigableAttribute.java, api/src/main/java/jakarta/data/metamodel/NumericAttribute.java, api/src/main/java/jakarta/data/metamodel/SortableAttribute.java, api/src/main/java/jakarta/data/metamodel/TextAttribute.java, api/src/main/java/jakarta/data/metamodel/impl/AttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/BasicAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/ComparableAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/NavigableAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/NumericAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/SortableAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/impl/TextAttributeRecord.java, api/src/test/java/jakarta/data/metamodel/AttributeTest.java, api/src/test/java/jakarta/data/metamodel/SortableAttributeTest.java, api/src/test/java/jakarta/data/metamodel/TextAttributeTest.java
Simplest possible solution to #1036.
=> Add Attribute.declaringType()

api/src/main/java/jakarta/data/metamodel/NumericExpression.java, api/src/main/java/jakarta/data/metamodel/expression/NumericCast.java, api/src/main/java/jakarta/data/metamodel/expression/NumericCastRecord.java
=> add numeric type promotions in simplest possible way

api/src/main/java/jakarta/data/metamodel/ComparableExpression.java, api/src/main/java/jakarta/data/metamodel/Expression.java, api/src/main/java/jakarta/data/metamodel/TextExpression.java, api/src/main/java/jakarta/data/metamodel/expression/FunctionExpression.java, api/src/main/java/jakarta/data/metamodel/expression/NumericFunctionExpression.java, api/src/main/java/jakarta/data/metamodel/expression/NumericFunctionExpressionRecord.java, api/src/main/java/jakarta/data/metamodel/expression/TextFunctionExpression.java, api/src/main/java/jakarta/data/metamodel/expression/TextFunctionExpressionRecord.java, api/src/test/java/jakarta/data/metamodel/expression/ExpressionTest.java
I believe that this is the correct way to handle inheritance.
=> accept supertype attributes in Expression methods

api/src/main/java/jakarta/data/metamodel/Attribute.java, api/src/main/java/jakarta/data/metamodel/ComparableAttribute.java, api/src/main/java/jakarta/data/metamodel/NavigableExpression.java, api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java, api/src/main/java/jakarta/data/metamodel/TemporalAttribute.java, api/src/main/java/jakarta/data/metamodel/TemporalAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/TemporalExpression.java, api/src/main/java/jakarta/data/metamodel/expression/CurrentDate.java, api/src/main/java/jakarta/data/metamodel/expression/CurrentDateTime.java, api/src/main/java/jakarta/data/metamodel/expression/CurrentTime.java, api/src/main/java/jakarta/data/metamodel/impl/TemporalAttributeRecord.java, api/src/main/java/jakarta/data/metamodel/path/TemporalPath.java, api/src/main/java/jakarta/data/metamodel/path/TemporalPathRecord.java, api/src/test/java/jakarta/data/metamodel/expression/TemporalExpressionTest.java, api/src/test/java/jakarta/data/mock/entity/_Book.java, spec/src/main/asciidoc/entity.asciidoc
Add TemporalAttribute and related static metamodel classes
Fixes #1022
=> add TemporalAttribute and related classes

api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java
A great work has been done on this point.
I included the `DisplayName` annotation to each scenario, including constraint validation, plus I've removed the warning annotation.
=> Enhance and include new test scenarions on the BasicRestrictionRecordTest

spec/src/main/asciidoc/chapters/license/license-efsl.adoc
Align with what I did in the Query spec.
=> deuglify the copypasta

api/src/test/java/jakarta/data/metamodel/impl/AttributeRecordTest.java, api/src/test/java/jakarta/data/metamodel/impl/SortableAttributeRecordTest.java, api/src/test/java/jakarta/data/metamodel/impl/TextAttributeRecordTest.java
I know this package is deprecated, but I would still love to have some tests to ensure the behavior.
=> Create test scenarions to the impl package

api/src/main/java/jakarta/data/metamodel/Attribute.java, api/src/main/java/jakarta/data/restrict/BasicRestriction.java, api/src/main/java/jakarta/data/restrict/BasicRestrictionRecord.java, api/src/main/java/jakarta/data/restrict/CompositeRestriction.java, api/src/main/java/jakarta/data/restrict/Restrict.java, api/src/main/java/jakarta/data/restrict/Restriction.java, api/src/test/java/jakarta/data/restrict/BasicRestrictionRecordTest.java, api/src/test/java/jakarta/data/restrict/CompositeRestrictionRecordTest.java, api/src/test/java/jakarta/data/restrict/TextRestrictionRecordTest.java
First item under #1086
Adds Javadoc for Restriction.  I think the Restriction interface and Restrict have remained fairly stable for a while now and should be safe to add Javadoc for.
=> Javadoc for Restriction

api/src/test/java/jakarta/data/expression/ExpressionTest.java, api/src/test/java/jakarta/data/expression/TemporalExpressionTest.java, api/src/test/java/jakarta/data/restrict/BasicRestrictionRecordTest.java, api/src/test/java/jakarta/data/restrict/RestrictTest.java, tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiCharacter.java, tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java, tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
=> squash warnings in IntelliJ

.github/workflows/ci.yml, .github/workflows/specification.yml, .github/workflows/update.yml, README.adoc, api/pom.xml, pom.xml, spec/README.adoc, tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc, tck-dist/src/main/starter/ee-pom.xml, tck-dist/src/main/starter/se-pom.xml, tck/pom.xml, tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java, tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java, tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_25
Changes the minimum java level of the project from Java 17 to Java 21.
=> refactor: java 17 -> 21 minimum

api/src/main/java/jakarta/data/expression/literal/NumericLiteralRecord.java, api/src/main/java/jakarta/data/expression/literal/TemporalLiteralRecord.java
Address 2 TODO comments in the code to replace with a switch statement after moving up to Java 21 compilation.
=> Address TODO to use switch after moving up to Java 21

api/src/main/java/jakarta/data/expression/ComparableExpression.java, api/src/main/java/jakarta/data/expression/Expression.java, api/src/main/java/jakarta/data/expression/NumericExpression.java, api/src/main/java/jakarta/data/expression/TemporalExpression.java, api/src/main/java/jakarta/data/expression/TextExpression.java, api/src/main/java/jakarta/data/metamodel/Attribute.java
This PR adds Javadoc for:
- ComparableExpression
- TemporalExpression
- TextExpression
- NumericExpression
=> javadoc for comparable expressions

api/src/main/java/jakarta/data/expression/function/NumericOperatorExpression.java, api/src/main/java/jakarta/data/expression/function/NumericOperatorExpressionRecord.java, api/src/main/java/jakarta/data/expression/function/TextFunctionExpressionRecord.java, api/src/test/java/jakarta/data/expression/function/FunctionTest.java
IllegalArgumentException for a couple of error paths due to bad input:
*  .divide(0)
*  .right(negative) and .left(negative)
=> IllegalArgumentException for division by 0 and negative RIGHT/LEFT size arg

api/pom.xml, pom.xml, spec/pom.xml, tck-dist/pom.xml, tck/pom.xml
Once we have already released version 1.0.1.
I need this dependency to start work with: 1.1.0-SNAPSHOT
=> Update snapshot versiont to 1.1.0

api/pom.xml
=> fix: add osgi manifest to api jar [1.0.1]

spec/src/main/asciidoc/entity.asciidoc, spec/src/main/asciidoc/repository.asciidoc
I've included the documentation spec of `Restriction`, which is based on what I am doing; thus, it does not mean that it is the right direction (I put it here also to discuss).
I wrote mainly to explain some corner cases that I encountered during the process.
=> Include more information on Restriction

spec/src/main/asciidoc/architecture.asciidoc, spec/src/main/asciidoc/repository.asciidoc, stateful/src/main/java/jakarta/data/repository/stateful/Merge.java
Posting this here to get feedback.
=> start defining what a stateful repository is

api/src/main/java/jakarta/data/constraint/Constraint.java, api/src/main/java/jakarta/data/constraint/Like.java, api/src/main/java/jakarta/data/constraint/package-info.java
Write Javadoc for Constraint and one subtype of Constraint (Like).  If this looks acceptable, we can go on to do likewise for the other subtypes.
=> Javadoc for Constraint and Like

api/src/main/java/jakarta/data/constraint/AtLeast.java, api/src/main/java/jakarta/data/constraint/AtMost.java, api/src/main/java/jakarta/data/constraint/Between.java, api/src/main/java/jakarta/data/constraint/Constraint.java, api/src/main/java/jakarta/data/constraint/GreaterThan.java, api/src/main/java/jakarta/data/constraint/LessThan.java, api/src/main/java/jakarta/data/constraint/NotBetween.java
Write javadoc for:
LessThan
GreaterThan
AtLeast
AtMost
Between
NotBetween
=> Javadoc for LT/GT/LTE/GTE/Between/NotBetween constraints

api/src/main/java/jakarta/data/constraint/EqualTo.java, api/src/main/java/jakarta/data/constraint/In.java, api/src/main/java/jakarta/data/constraint/Like.java, api/src/main/java/jakarta/data/constraint/NotEqualTo.java, api/src/main/java/jakarta/data/constraint/NotIn.java, api/src/main/java/jakarta/data/constraint/NotLike.java, api/src/main/java/jakarta/data/constraint/NotNull.java, api/src/main/java/jakarta/data/constraint/Null.java
Add Javadoc to remaining constraint classes:
`EqualTo`
`NotEqualTo`
`In`
`NotIn`
`Null`
`NotNull`
`NotLike`
=> Javadoc for remaining constraints

pom.xml
Test suggestion provided here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6635#note_5245180
Reference: https://github.com/jakartaee/data/issues/1168
=> test: snapshot publishing

pom.xml
This reverts commit e1c87b69d23f33bd616eff03ed1e2a9904b84a57
Based on this comment: https://github.com/jakartaee/data/pull/986#issuecomment-3353400517
=> Revert "fix build"

.github/workflows/ci.yml, api/pom.xml, api/src/main/java/jakarta/data/metamodel/Attribute.java, api/src/main/java/jakarta/data/page/Page.java, pom.xml, spec/pom.xml, tck-dist/pom.xml, tck/pom.xml
I was able to publish a snapshot in the concurrency project with a similar configuration.
See: https://github.com/jakartaee/concurrency/pull/760
=> refactor: update to project 2.0.0-SNAPSHOT
