README.md

Linking to the meeting schedule and minutes will help participants find the information more quickly.

Add meeting minutes and calendar links on readme/main page

---

api/src/main/java/jakarta/data/repository/Limit.java
api/src/main/java/jakarta/data/repository/Pageable.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/jakarta/data/repository/Sort.java
spec/src/main/asciidoc/repository.asciidoc

Include Limit in main spec asciidoc.
Update Limit JavaDoc to state incompatibility with Pageable being specified at same time.
Update Pageable JavaDoc to state incompatibility with Limit being specified at same time.
Update Sort JavaDoc with incompatibilities and fix JavaDoc warnings.
Update Repository JavaDoc to replace the TODO with links to Pageable and Sort.
Also added some more examples to the JavaDocs while updating those areas.

remaining documentation updates for Limit

---

api/src/main/java/jakarta/data/repository/Limit.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/test/java/jakarta/data/repository/LimitTest.java

Fixes #35
Renames to the following: `Limit.range(101, 200)`

new name for method that creates range limits

---

CHANGELOG.md
api/pom.xml
api/src/test/java/jakarta/data/repository/PageableTest.java
api/src/test/java/jakarta/data/repository/SortTest.java
pom.xml

This PR replace Hamcrest assertion library by AssertJ to add more fluent asserts.
- jakarta-data-api
- Removed `hamcrest-all` in favour of `assertj-core`
- Changed the assertions in `PageableTest` and `SortTest`
- Removed redundant tests on `SortTest`
- jakarta-data-parent
- Updated the following libraries
- `mockito`.version` to `4.8.0`
- `junit` to `5.9.0`
- Fix typo on `mockito.version`

Replacing assertion libraries: Hamcrest by AssertJ

---

spec/pom.xml

Avoid autodiscovery and:
```
[INFO] sourceDirectory /usr/local/apps/jakartaee-apps/data-api/spec/src/docs/asciidoc does not exist
[INFO] sourceDirectory /usr/local/apps/jakartaee-apps/data-api/spec/src/asciidoc does not exist
```
Ref: https://www.eclipse.org/lists/data-dev/msg00048.html

Explicit sourceDirectory

---

api/src/test/java/jakarta/data/repository/LimitTest.java

Applied through
```shell
mvn org.openrewrite.maven:rewrite-maven-plugin:4.35.1:init \
-Ddependencies=org.openrewrite.recipe:rewrite-testing-frameworks:1.29.0 \
-DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
mvn rewrite:run
```
@eliasnogueira as we discussed this afternoon. :) Continues on from #33 
Figured it's better to be consistent about which assertion library to use rather than use a mix of JUnit 5 & AssertJ.

Consistently use AssertJ instead of JUnit 5 Assertions

---

spec/README.adoc

In keeping aligned with the other specifications, this PR adds a README.adoc file that describes contributing to the documentation.

Add README.adoc file to spec directory

---

api/src/main/java/jakarta/data/repository/Query.java

When name-pattern-based repository methods are used with pagination, a Jakarta Data provider is able to use that same information to query for total page/number of elements count. However, when the user provides a complex query via the `@Query` annotation, the Jakarta Data provider should not be expected parse the query language or modify the user-provided query to obtain the total count of elements/pages.  This is solved in [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/Query.html#countQuery--) and [Micronaut](https://micronaut-projects.github.io/micronaut-data/2.4.4/api/io/micronaut/data/annotation/Query.html#countQuery--) by allowing a counting query to be optionally specified on the `@Query` annotation.  Jakarta Data …

page count when using Query annotation

---

api/src/main/java/jakarta/data/repository/Slice.java
api/src/main/java/jakarta/data/repository/Streamable.java

As @odrotbohm recommendation, I've created this PR for this discussion:
https://github.com/jakartaee/data/pull/37#issuecomment-1286980442
The main reason for this PR is that the Stream makes sense to handle with Data at Jakarta Data. However, the structure should consider the resource available for it.
> Spring Data's Page implements Streamable, an extension of Iterable that exposes a stream() method defaulting to non-parallel streaming.
https://github.com/jakartaee/data/issues/36#issuecomment-1268074831
So, I created this PR to start the discussion on the ```Streamable``` 
The biggest inspiration comes from [Spring Data Commons](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/util/Streamable.java), where I took a feel method to …

Add Streamable interface

---

api/src/main/java/jakarta/data/repository/KeysetAwareSlice.java
api/src/main/java/jakarta/data/repository/KeysetPageable.java
api/src/main/java/jakarta/data/repository/KeysetPagination.java
api/src/main/java/jakarta/data/repository/Page.java
api/src/main/java/jakarta/data/repository/Pageable.java
api/src/main/java/jakarta/data/repository/Pagination.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Slice.java
api/src/main/java/jakarta/data/repository/Sort.java
api/src/test/java/jakarta/data/repository/KeysetPageableTest.java
api/src/test/java/jakarta/data/repository/PageableTest.java
api/src/test/java/jakarta/data/repository/SortTest.java

Alters the API to use record-style accessors. To avoid confusion the `page(int)` and `size(int)` methods are renamed `newPage(int)` and `newSize(int)` respectively. Fixes #70

Use record-style accessors for API

---

api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/jakarta/data/repository/Streamable.java
spec/src/main/asciidoc/repository.asciidoc

This pull removes TODO comments from specification JavaDoc, in a few cases by addressing them, but in most cases by moving the comment to after the JavaDoc under an `// TODO` comment that won't get generated into the JavaDoc that users will see.
It also corrects the paragraph tags in the Repository class JavaDoc.
I also fixed 2 places in the asciidoc where we had examples still using method names that had since been renamed and clarified the Streamable return type with what I think was the decision (only reads the data once) and added a note that when Stream is returned from a repository method, the user needs to ensure it gets closed.  I don't if Jakarta Data providers will actually be streaming results from the database vs just what was read in advance as Streamable does, but it will be …

remove TODO comments from spec JavaDoc

---

api/src/main/java/jakarta/data/repository/KeysetAwareSlice.java
spec/src/main/asciidoc/repository.asciidoc

Specification should define that UnsupportedOperationException be raised when a repository method is requested to perform keyset pagination but the underlying database is incapable of it.

Define error for when database cannot do keyset pagination

---

api/src/main/java/jakarta/data/repository/Pageable.java
api/src/main/java/jakarta/data/repository/Pagination.java
api/src/test/java/jakarta/data/repository/KeysetPageableTest.java
api/src/test/java/jakarta/data/repository/PageableTest.java

Signed-off-by: Otavio Santana <otaviopolianasantana@gmail.com>
Update API to use:
```java
Pageable pageable = Pageable.size(50)
.page(5)
.sort(Sort.asc("lastName"), Sort.asc("firstName), Sort.asc("id"))
.afterKeyset(lname, fname, id);
```
I checked in `Pageable` and `Limit` both use the `of` as a prefix on the method factory on the majority.
Ref: https://github.com/jakartaee/data/issues/67

Inconsistent Pageable factory methods

---

tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Assertion.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/AssertionNameGenerator.java
tck/src/main/java/ee/jakarta/tck/data/framework/servlet/URLBuilder.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
tck/src/test/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessorTest.java
tck/src/test/java/ee/jakarta/tck/data/framework/junit/extensions/AssertionNameGeneratorTest.java
tck/src/test/java/ee/jakarta/tck/data/framework/servlet/URLBuilderTest.java

Introduce unit tests to verify behavior of the `ee.jakarta.tck.data.framework.*` packages.
We want to verify the following: 
- TCKArchiveProcessor correctly adds framework packages based on archive type and test class annotations.
- AssertionNameGenerator correctly modifies test classes with the platform, and test methods with an assertion ID
- URLBuilder correctly constructs a URL with given paths and queries. 
This testing relieved some edge cases that I had to fix.

Write unit tests for TCK Frameworks

---

api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Sort.java

Fixes #94 issue where JavaDoc for 2 classes wasn't update when Sort was added to Pageable.

javadoc update missed when Sort was added to Pageable

---

api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/jakarta/data/repository/Sort.java
api/src/test/java/jakarta/data/repository/SortTest.java
spec/src/main/asciidoc/repository.asciidoc

Existing repository implementations have repository keywords ([Micronaut](https://micronaut-projects.github.io/micronaut-data/latest/guide/), [Spring](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/)) and other [methods](https://docs.spring.io/spring-data/commons/docs/1.9.1.RELEASE/api/org/springframework/data/domain/Sort.Order.html#ignoreCase--) to indicate case insensitive comparisons for string properties.  These are useful so this pull adds to Jakarta Data.

Case insensitive comparisons

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

[Micronaut](https://micronaut-projects.github.io/micronaut-data/latest/guide/) and [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/) have repository keywords for boolean true/false conditions and checking for null.  Jakarta Data doesn't have these documented yet.  This pull adds them.

repository keywords for boolean conditions and Null

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

[Micronaut](https://micronaut-projects.github.io/micronaut-data/latest/guide/) and [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/) have repository keywords to check for empty collections. This pull adds Empty to Jakarta Data documentation, which currently lacks it.

repository keyword for Empty

---

CHANGELOG.adoc
api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

This PR creates a release version to 1.0.0-b1.
As we discussed, the first release primarily aims to receive feedback from the community and see some implementations/vendor feedback.

Release version 1.0.0-b1

---

api/src/main/java/jakarta/data/exceptions/DataConnectionException.java
api/src/main/java/jakarta/data/exceptions/DataException.java
api/src/main/java/jakarta/data/exceptions/EmptyResultException.java
api/src/main/java/jakarta/data/exceptions/MappingException.java
api/src/main/java/jakarta/data/exceptions/NonUniqueResultException.java
api/src/main/java/jakarta/data/repository/Repository.java

The exception classes in Jakarta Data are missing serialVersionUID (they are Serializable because they inherit from Throwable) which could make them incompatible across JVMs that generate the value differently. This also shows as a warning in some editors.
Also, there are JavaDoc warnings from some of the exception classes for an undocumented method parameter (plus 1 other JavaDoc warning that I'll fix here as well)
```
[WARNING] Javadoc Warnings
[WARNING] /Users/njr/lgit/data/api/src/main/java/jakarta/data/repository/Repository.java:270: warning: empty <p> tag
[WARNING] * <p>
[WARNING] ^
[WARNING] /Users/njr/lgit/data/api/src/main/java/jakarta/data/exceptions/DataConnectionException.java:43: warning: no @param for cause
[WARNING] public DataConnectionException(String message, Throwable …
```

JavaDoc warnings and lack of serialVersionUID on exceptions

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

I made a mistake in an earlier pull while discussing usage of `Id` in query by method name, erroneously stating that the name/value from the `@Column` or `@Id` annotations could be used as the entity property name. The `@Column` name attribute has a different purpose in JPA - it's for the database column name, not an entity property name, which can be easily verified in JPQL. We should correct this in the spec and better clarify.

Clarify entity property names

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

Clarify entity models in documentation and include example entities.
Relates to #112

include entity examples and address TODO in documentation

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

The specification should document the precedence for `And` and `Or` so that users can be assured what behavior they can rely on getting when writing a repository method like,
`findByNumDependantsGreaterThanOrFilingStatusAndIncomeBetween`
Users will likely expect to get the precedence [defined by JPQL](https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1.html#operators-and-operator-precedence) or by Java, which both have `And` taking precedence and being evaluated first.
Also, I spotted a typo in the same file where a sentence is missing the verb, so I've corrected that as well in this pull.

Document precedence of logical operators

---

api/src/main/java/jakarta/data/repository/Limit.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Pageable.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Sort.java
spec/src/main/asciidoc/repository.asciidoc

Fixes #116 - defines precedence for sort criteria according to the discussion in that issue.

precedence for sort criteria

---

api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Pageable.java
api/src/main/java/jakarta/data/repository/Sort.java
spec/src/main/asciidoc/repository.asciidoc

It was brought up by @otaviojava in an issue discussion and on the previous Jakarta Data call that we need a way in the spec to acknowledge that databases will have limited support for some capabilities, specifically around ordering.  In cases like this, the Jakarta Data specification can simply call out that the Jakarta Data provider is expected to raise an error for what the underlying database itself doesn't support.  That way Jakarta Data providers themselves can remain compliant regardless of whether the database is or is not capable of every requested aspect of the sort criteria.  This will have value to more than just NoSQL.  I tried out a scenario with Jakarta Persistence where I attempted to specify ordering based on a collection valued attribute (as opposed to a numeric or …

Exception when database not capable of function

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

Come up with a set of rules for CDI extensions to reduce/avoid colliding on the same repositories when there are multiple providers active in the system.

Avoiding conflicts between CDI extensions

---

tck-dist/src/main/asciidoc/sections/06requirements.adoc
tck-dist/src/main/asciidoc/sections/07.1se-mode.adoc
tck-dist/src/main/asciidoc/sections/07.2ee-mode.adoc
tck-dist/src/main/asciidoc/sections/07.aentity-modes.adoc
tck-dist/src/main/java/ee/jakarta/tck/data/metadata/CollectMetaData.java
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/core/example/CDIExampleTests.java
tck/src/main/java/ee/jakarta/tck/data/core/nosql/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/core/nosql/example/NoSQLEntityTests.java
tck/src/main/java/ee/jakarta/tck/data/core/nosql/example/Order.java
tck/src/main/java/ee/jakarta/tck/data/core/nosql/example/Product.java
tck/src/main/java/ee/jakarta/tck/data/core/persistence/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/core/persistence/example/Order.java
tck/src/main/java/ee/jakarta/tck/data/core/persistence/example/PersistenceEntityTests.java
tck/src/main/java/ee/jakarta/tck/data/core/persistence/example/Product.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Assertion.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/AssertionExtension.java
tck/src/main/java/ee/jakarta/tck/data/standalone/example/StandaloneExampleTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/signature/SignatureTests.java
tck/src/main/java/ee/jakarta/tck/data/web/example/ComplexServletTests.java
tck/src/main/java/ee/jakarta/tck/data/web/example/SimpleServletExampleTests.java

Related to: #119 
Introduce a method to test the Persistence Entity and NoSQL Entity separately. 
This will be for cases where we want to test the specific functionality of either Entity that does not apply to the other. 
⚠️: The example tests I've written are not the intended use case (to duplicate code) they are just being used to have some sample tests available to reference once we start writing more complex tests.

Allow for specific entity testing

---

spec/src/main/asciidoc/repository.asciidoc

Related to #119 
- Fixes spec documentation: `jakarta.nosql.mapping.*` -> `jakarta.nosql.*`
- Discourages applications from using both Entity annotations on the same class
- Document that the Repository is only responsible for using the entity it supports.

TCK needs to be able to put both entity annotations on same entity

---

api/src/main/java/jakarta/data/repository/Repository.java
spec/src/main/asciidoc/repository.asciidoc

The spec needs to state what must happen if there is a JTA transaction already on the thread when a repository method is invoked so that users can know what to expect, both for resources types that are enlistable (these participate in the transaction) and for those which are not (these do not participate in the transaction).  The spec should also acknowledge that a failure running a repository method might cause a transaction to be marked as rollback-only (JPA does this in some cases) so that users are not surprised by that behavior.

Document interoperability with Jakarta Transactions

---

.github/workflows/java-17.yml
README.adoc
api/src/main/java/jakarta/data/repository/Limit.java
api/src/main/java/jakarta/data/repository/Pagination.java
api/src/main/java/jakarta/data/repository/Sort.java
pom.xml
spec/README.adoc
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck/pom.xml

[Jakarta EE 11](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee11/JakartaEE11ReleasePlan) is looking to make Java 21 the minimum supported runtime level.  Java 21 isn't available yet, but a step toward getting there is to update from Java 11 to Java 17, the most recent long term support release of Java that is currently available.  This enables us to update some classes to utilize Java records as we previously voted.  At the time, those classes were updated to look like Java records in the way that methods were formed, but with compilation still at Java 11, they still included implementation of accessor methods/equals/toString/hashCode and so forth simulating what Java records would provide.
This can be looked at after Otavio gets beta 2 out.

Compile against Java 17

---

api/src/main/java/jakarta/data/repository/Repository.java

Have a simple identifier that can optionally be specified on a repository that Jakarta Data providers can use to distinguish which vendor-specific configuration is wanted for the repository.  In a future version of the spec, this could be reused to identify a Jakarta Config base configuration path, but should hopefully be something that Jakarta Data providers can use in a vendor-specific way as well.

Minimal identifier to enable vendor configuration

---

api/src/main/java/jakarta/data/repository/Repository.java

There is a TODO comment to reserve any keywords that we might want to add meaning for in the future.  This is a good idea so that we avoid breaking changes to applications that are written with v1.0 so that they can move up and get identical behavior without experiencing breakages.  It informs them of particular keywords to avoid.  In this pull, I looked over the JPQL language and identified areas that query-by-method-name might possibly some day cover, but doesn't currently.  This includes abilities like extracting a particular component of a date, length of a string or size of a collection, rounding.  We can reserve the keywords now in case we ever want to leverage these capabilities.
Here are a few examples of things you cannot do now, but conceivably could be added via what Jakarta …

Address the TODO to reserve keywords for future

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

This adds the TCK tests for single Sort parameter, two Sort parameters, varargs Sort parameters, and KeysetAwareSlice from #133.

TCK tests for Sort parameters and TCK tests for KeysetAwareSlice

---

tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKFrameworkAppender.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/StandaloneExtension.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/Populator.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestProperty.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestPropertyHandler.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestPropertyUtility.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/NoSQLEntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/Product.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/example/PersistenceEntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/example/Product.java

- decouple test property enum from utility methods. 
- move read/write entity-specific tests to Standalone where they actually belong
- create a standard eventual consistency method for use in read-only tests and read/write tests.
Fixes #136

Eventual consistancy for read/write tests

---

api/src/main/java/jakarta/data/exceptions/DataConsistencyException.java
api/src/main/java/jakarta/data/exceptions/OptimisticLockingFailureException.java
api/src/main/java/jakarta/data/repository/CrudRepository.java

fixes #152
Among the different options here, comparing all entity attributes wouldn't always be achievable and likely wouldn't perform well either. Going with the approach that Spring has to consider the id and version (if versioned) seems best.  It makes sense to raise an error given that return type is void and the user needs to be informed somehow that their requested operation cannot be honored.

complete the documentation of CrudRepository.delete

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharactersPopulator.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Add these 5 tests for Page from #133
- Request the first Page of 10 results, expecting to find all 10. From the Page, verify the totalElements and totalPages expected.
- Request the third Page of 10 results, expecting to find all 10. Request the next Page via nextPageable, expecting page number 4 and another 10 results.
- Request the last Page of up to 10 results, expecting to find the final 3.
- Request a Page higher than the last Page, expecting an empty Page with 0 results.
- Request a Page of results where none match the query, expecting an empty Page with 0 results.
This also avoids writing the ASCII NULL character (0) to the database, which some databases don't support.

TCK tests for Page

---

.github/workflows/java-CI.yml
tck-dist/src/main/asciidoc/sections/05inventory.adoc
tck-dist/src/main/asciidoc/sections/07.2ee-mode.adoc
tck-dist/src/main/asciidoc/sections/10signature.adoc
tck-dist/src/main/assembly/assembly.xml
tck-dist/src/main/starter/ee-pom.xml
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKFrameworkAppender.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestData.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestEE.java
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

Noticed some issues when compiling and running using Java 21. 
- Updated our CI build to use Java 21 to verify we do not introduce breaking changes
- Updates signature test files to have two versions, one for Java 17 and one for Java 21
- Improved the signature file generation to automatically convert JDK modules to classes
- Removed the need to export the signature plugin to a Jakarta Platform when running in EE mode

Updates for Java 21

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Test for these TCK scenarios from #133
- Use the findAll method of a repository that inherits from PageableRepository to request a Page 2 of size 12, specifying a Pageable that requires a mixture of ascending and descending sort. Verify the page contains all 12 expected entities, sorted according to the mixture of ascending and descending sort orders specified.
- Use a repository that inherits from CrudRepository and adds some methods of its own. Use both built-in methods and the additional methods.
- Use a repository method findFirstBy... that returns the first entity value where multiple results would otherwise be found.
- Use a repository method findFirst3By... that returns the first 3 results.

tests for findFirst, CrudRepository and PageableRepository

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Tests for these TCK scenarios from #133
- Use a repository method with Or, expecting MappingException if the underlying database is not capable.
- Use a repository method with GreaterThan / Use a repository method existsByIdGreaterThan... confirming the correct boolean is returned
- Use a repository method with LessThan / Use a repository method countByIdLessThan... confirming the correct count is returned
- Use a repository method with In

Tests for keywords: Or, In, LessThan, GreaterThan, ExistsBy, CountBy

---

pom.xml
tck-dist/src/main/asciidoc/sections/05inventory.adoc
tck-dist/src/main/assembly/assembly.xml
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck-dist/src/main/starter/src/test/resources/arquillian.xml
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTest.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestData.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestEE.java
tck/src/main/java/ee/jakarta/tck/data/standalone/signature/SignatureTests.java

Discovered a bug in the TCK where we were automatically appending the packages from the Signature Test plugin library to the application before being deployed to the Jakarta Profile. 
I didn't realize that message files were not being included, this change will add the entire signature test plugin library under the `lib` directory of the .war archive. 
This change has no affect on Standalone mode. 
(also fixed some whitespace inconsistencies in the TCK)

Fix TCK signature testing

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

TCK tests covering scenarios under #133
- Use a repository method with IgnoreCase.
- Use a repository method with Null.
- Use a repository method with False.
- Use a repository method with Contains (substring test only).

TCK tests for IgnoreCase, Contains (substring), True, False

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Adds the following tests from #133
- Use a repository that inherits some if its methods from another interface.
- Use a default method from a repository interface where the default method invokes other repository methods.
- Use a repository method with Not

Tests for default methods, common interfaces, Not

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Write TCK tests for the following scenarios from #133
- Request the first KeysetAwarePage of 8 results, expecting to find all 8, then request the next KeysetAwarePage after the keyset of the last entry of the page, expecting to find the next 8. Or validate that UnsupportedOperationException is raised to indicate that the underlying database is incapable of keyset pagination.
- Request a KeysetAwarePage of 7 results after the keyset of the 20th result, expecting to find the next 7 results. Then request the KeysetAwarePage before the keyset of the first entry of the page, expecting to find the previous 7 results. Then request the KeysetAwarePage after the last entry of the page, expecting to find the next 7. Or validate that UnsupportedOperationException is raised to indicate that the …

Tests for KeysetAwarePage

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc

This is step 1 of #223 to clarify documentation around built-in super interfaces for repositories.

clarifications on built-in repository super interfaces

---

tck-dist/pom.xml

The jruby version needs to be updated manually, since dependabot recommends an incompatible version. This PR updates to the latest version on the 9.3 stream. 
After merging this, PR #168 can be canceled.

Updating jruby version

---

api/src/main/java/jakarta/data/repository/CrudRepository.java

This is another step toward #229 to more clearly define behavior of the save operation.
In this pull, documentation is added to explain what the return value means and to direct users not to continue to use the entity that is supplied as a parameter, because the spec is not making any guarantees about whether that will include updates to entity attributes that get automatically updated on save, but the result value will be guaranteed to include those updates if there are any.
Also, I noticed a mistake that I missed spotting while reviewing the previous round of updates to the save operation, where, as literally read, it accidentally forbids allowing a new entity with a non-null ID value to be inserted into the database.  I'm correcting that as well.
The Jakarta Validation behavior that we …

more documentation about the save parameter and return value

---

spec/src/main/asciidoc/repository.asciidoc

A few keywords are defined in the keyword list in the JavaDoc and the BNF but are missing from the keyword list in the spec document.  This pull makes the keyword list in the spec doc consistent with the other two.

Keyword list consistency with JavaDoc and BNF

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc

Write up the approach for obtaining the EntityManager/DataSource/Connection that was discussed and decided upon during the Jakarta Data call.
fixes #202

accessor method to obtain EntityManager

---

api/src/main/java/module-info.java

We should include the limitations for each database type in the JavaDoc tables of keywords.  This information is copied from  #247 where it was added to the corresponding tables in the specification document.
Also included in the pull, I moved the Asc, Desc, and OrderBy keywords into their own table, so that we have a table for subject keywords, another for predicate keywords, and another for order clause keywords.  That seems the most straightforward for users to reference when writing queries.

Include per-database-type keyword limitations in JavaDoc

---

api/src/main/java/module-info.java

fixes #256 
I confirmed that including api is non-standard for jakarta projects.

update module-info to remove api

---

api/src/main/java/module-info.java

#260 added rules for parameter-based queries to the spec doc based on #255 but we also need to document parameter-based queries in the JavaDoc.  This pull adds that.

JavaDoc needs to include parameter-based queries

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

CrudRepository has two methods that don't follow the rules in the spec:
```
findAllById(Iterable<K> ids);
deleteAllById(Iterable<K> ids);
```
If a user added these methods to their own repository interface (which is something we explicitly state in the spec can be done), per the rules of the spec, it would mean an equality comparison where the id is equal to the Iterable, which isn't what is wanted.  What is really wanted here is provided by the `In` keyword, which matches any item in the collection.
Names that are consistent with the spec rules would be:
```
findAllByIdIn(Iterable<K> ids);
deleteAllByIdIn(Iterable<K> ids);
```
or
```
findByIdIn(Iterable<K> ids);
deleteByIdIn(Iterable<K> ids);
```
This pull updates to the latter.

Fix two CrudRepository method names that do not follow the spec rules

---

README.adoc
api/src/main/java/module-info.java
spec/src/main/asciidoc/jakarta-ee.adoc
spec/src/main/asciidoc/portability.asciidoc
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

@otaviojava renamed CrudRepository to BasicRepository under #274 , covering the spec API classes and signature tests.  The spec doc, JavaDoc, and TCK need to be made consistent with this.

Renames that were missed in JavaDoc, spec, and TCK

---

tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

This area of the specification should be consistent in how is currently written and Gavin's pull to make changes, so we should be able to add TCK tests.  The following scenarios are included in this pull:
- Find a single entity, querying by entity attributes with names that match the method parameter names.
- Find a single entity that might or might not exist (return type of Optional), querying by entity attributes with names that match the method parameter names.
- Find a list of entities, querying by entity attributes with names that match the method parameter names, with results capped by a Limit parameter and sorted according to a variable arguments Sort parameter.
- Find a page of entities, with entity attributes identified by the parameter names and matching the parameter values.

TCK tests for find queries using parameter names

---

api/src/main/java/jakarta/data/exceptions/EntityExistsException.java
api/src/main/java/jakarta/data/repository/BasicRepository.java

It was just decided on today's Jakarta Data call that we will include the insert and update methods on the built-in repository interface.  This pull copies over the updates for it from the #270 commits.

insert and update methods on built-in repository

---

api/src/main/resources/checkstyle.xml
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacter_.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java

Add tests for StaticMetamodel, used to obtain entity attribute names in a type-safe manner and ascending/descending Sort from the Attribute, also in a type-safe manner.

tests for StaticMetamodel

---

spec/src/main/asciidoc/repository.asciidoc

This draft implements the ideas proposed in #223.
This is unfinished, since it updates only the specification, and not the Java APIs.
I'm sending it "early" for the purpose of obtaining feedback.

repository programming model

---

CHANGELOG.adoc
api/src/main/java/jakarta/data/repository/CrudRepository.java

- Make the return an instance instead of a void or boolean
- Enhance documentation explaining that returning the same instance to both methods is ok.
- Enable Data-driven domain-supporting records in all methods.
- Explaining more about the exceptions when the database does not support ACID.
- It would be amazing to have support to record even if JPA does not support it.
- Non-ACID databases can have insert and update methods but with different consistency strategies, such as clock-vector, read-repair, or any async handshake.
- I cannot assume anymore the NoSQL type as we did with the data structure, 
⚠️ it is a Pandora's. I need as much help as possible to support both database engines.

Make insert and update method work also with NoSQL databases

---

tck/pom.xml
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

I intentionally left out signatures for the `jakarta.data.model` package from the M1 TCK release because: 
1. There was ongoing discussions about this API
2. TCKs are not even required for M1 releases
Opening this PR now to make sure this package is accounted for in future pulls. 
Related #267 #296

Update signatures after M1

---

api/pom.xml
api/src/main/java/jakarta/data/model/StaticMetamodel.java
pom.xml
spec/src/main/asciidoc/repository.asciidoc
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiChar_.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacter_.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

This pull adds a TCK test to include a generated static metamodel class.  It also adds spec language to require the `@Generated` annotation on such classes so that Jakarta Data providers can optimize not to attempt initialization of generated metamodel classes that already have implementation.

TCK test for metamodel class generated at build time

---

tck-dist/pom.xml

Still updating jruby manually, waiting on the asciidoctorj 3.0.0 release.
Whichever committer merges this should also cancel https://github.com/jakartaee/data/pull/301

Updating jruby dependency

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java

A couple of TCK tests that were written prior to the spec changes to define lifecycle methods are lacking the `@Save` annotation.  It needs to be added so that the tests can be valid per the requirements of the spec.

TCK tests are missing the Save annotation on lifecycle methods

---

api/src/main/java/jakarta/data/repository/Delete.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

Add TCK for Insert, Update, and Delete life cycle methods.
Cover both single entity as well as multiple entities in the parameter.
Use an entity with a generated version and confirm it gets updated and is used to make updates.
Confirm that exceptions are raised per the spec requirements.
I also removed two extra `*` characters that I noticed in JavaDoc.

TCK tests for life cycle methods

---

api/src/main/java/module-info.java

Include the precedence for interpreting repository methods in the JavaDoc as well so that users will be able to reference it when writing repository methods.  This pull also includes minor clarifications to ensure consistency of the JavaDoc with the specification document.

Include precedence for repository methods in user-facing JavaDoc

---

spec/src/main/asciidoc/repository.asciidoc

Currently, we have the entity in the middle of the spec, breaking all the discussions about the repository.
The proposal is to move right after the introduction to the repository, thus keeping the flow going deep about the repository features.

Change the entity definition to the begin

---

spec/src/main/asciidoc/repository.asciidoc

Fixes #332 to have a better description of the example that calls out starting with an offset.

Clarify description of pagination approach used in example

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/jakarta-ee.adoc

Fixes #224 for Jakarta Data 1.0.  Subsequent versions of the specification can look into whether we would like to have modes that would externalize the concept of persistence context to applications.

document persistence context requirements for initial version of spec

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/CustomRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add TCK tests:
Use count and exists methods where the primary entity class is inferred from the life cycle methods.
Use a parameter-based find operation that uses the By annotation to identify the entity attribute names.

TCK tests for primary entity type and By

---

api/src/main/java/jakarta/data/package-info.java
api/src/main/java/jakarta/data/page/package-info.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/jakarta/data/repository/package-info.java

It is likely that users will find the JavaDoc via a number of different entry points, such as google searches for a particular spec interface.  This pull cleans up some package level JavaDoc and adds links to our main overview JavaDoc page to help users be able to locate it even if they had a different starting point and it doesn't otherwise occur to them to click on the link to the Module javadoc.

help users locate the main Jakarta Data overview page in JavaDoc

---

spec/src/main/asciidoc/repository.asciidoc

Review section 2.2: Entity Classes.
Entity classes ought to be a top level section of its own rather than placed under Repository in case the Jakarta Data spec ends up supporting  entities outside of a repository (such as via a static metamodel or template) at some point in the future, so I have adjusted some sections under the second commit of this pull to achieve that.  The Additional examples didn't fit well in the hierarchy after that and I realized they are mostly redundant, so I moved one that isn't redundant to its corresponding section and otherwise removed that section.  I think those examples used to have a different purpose back when we had a different understanding of what parameter-based automatic queries was and they ended up being converted into duplicates.

Review of Entity Classes section

---

spec/src/main/asciidoc/repository.asciidoc

There is one issue in this section that required some rearrangement of sections.  The spec says that "The Jakarta Data specification supports two types of repositories.  The first type consists of ..." and goes on an on about the first type, covering with multiple paragraphs and examples before transitioning into some general aspect that would apply to both types.  Long before this point, the user is already lost wondering why they haven't heard of a second type, which eventually appears even further along in the document.  I'm proposing to correct this by moving the common aspects to before the discussion of the type types, and then creating headings for the two types to clearly delineate them and make it obvious to the user that the spec does indeed discuss as second type and where to …

proofread section 2 Repository and 2.1 Repositories on Jakarta Data

---

spec/src/main/asciidoc/repository.asciidoc

Proofread section 4 on Repository Interfaces and all subsection except for 4.8 Pagination.
Section 4.5.2 on Entity Property Names has examples where the discussion is ambiguous because the entity property name and type are the same: `Address address` and `ZipCode zipCode`.  In order to make it clear which between the property name vs the property type is being referred to, I am changing the types to `MailingAddress address` and `int zipCode`.  Beyond this pull, this section needs some consideration as to whether its content is appropriate to a specification.  It seems to describe how a particular implementation's algorithm deals with certain examples rather than specifying requirements that implementations must meet.  I'll note this separately under #228 so that we remember to revisit it.

Review section 4 on Repository Interfaces, except for pagination

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/jakarta-ee.adoc

Review Section 5 on Interoperability with Jakarta EE Specifications.
I noticed that this section contains general requirements for Jakarta Data providers that apply regardless of whether they are used within Jakarta EE products, so I have moved those parts to a new section just prior to Interoperability with other Jakarta EE Specifications, such that there is now a section 5 for Jakarta Data providers and section 6 for Interoperability with other Jakarta EE Specifications.

review section 5: Interoperability with Jakarta EE specs

---

spec/src/main/asciidoc/portability.asciidoc

The section on Portability in Jakarta Data needed some more specifics, including calling out a minimal list of JPA annotations that must be supported.  We can't just say everything you can define on a JPA entity is supported, because our specification doesn't have the detail to define how the integration would work. For example, JPA will let you define composite IDs, but we don't currently say anything about how that would integrate with Jakarta Data and what it would mean to repository queries and so forth, so we should leave that one out for now.

review of section 7 on Portability

---

spec/src/main/asciidoc/repository.asciidoc

On the Jakarta Data call, Otavio asked that I add a keyset cursor-based pagination example scenario similar to what he wrote for offset-based pagination.  This pull adds it, using the same example data from the offset scenario. I updated one of the entities so that it has the same name as another, and the keyset scenario includes removing the duplicate as it is stepping through the pages of results such that an entity would be skipped (due to shifted offset) after deletion if using offset-based pagination, but with keyset cusror-based pagination, it finds the entity based on the cursor position and does not skip.

Include example with data for keyset pagination

---

api/src/main/java/module-info.java

It is difficult to visually identify one row from the next in tables within the JavaDoc. This pull adds shading for alternate rows to make the documentation readable.  Unfortuntately the nth-child(even) approach to automatic applying across the table requires the style element which is not allowed in JavaDoc, so I had to specify explicitly on each row, which is more tedious but has the same improvement for the reader.
Also, I spotted outdated references to "find..." that refer to a predecessor of the Automatic Query Methods / parameter-based conditions.  This pattern now allows for flexible naming of methods (they don't need to begin with find... anymore), so I removed those references from the table and added an explanation of how to locate the information in the table for the …

improve visibility of table rows in javadoc

---

api/src/main/java/jakarta/data/page/KeysetAwarePage.java
api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
api/src/main/java/jakarta/data/page/Page.java
api/src/main/java/jakarta/data/page/Pageable.java
api/src/main/java/jakarta/data/page/Slice.java
api/src/main/java/jakarta/data/page/package-info.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/test/java/jakarta/data/page/KeysetPageableTest.java
spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc

Proofread all of the JavaDoc in the jakarta.data.page package.
I also cleaned up a few compile warnings that I noticed in unit test (missing cast of null value to varargs method parameter type) and another annotation class (missing JavaDoc).

review of pagination JavaDoc

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/Sort.java
api/src/main/java/jakarta/data/Streamable.java

Proofreading of JavaDoc in the jakarta.data package.
I noticed that the code example for the Limit class had a long JPQL query on it that obscures some of the detail that the example tries to get across, so I switched it to a more concise automatic query method.  Hopefully this makes it easier to focus on the Limit aspects of it.

review of JavaDoc in the jakarta.data package

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/jakarta/data/repository/By.java
api/src/main/java/jakarta/data/repository/CrudRepository.java
api/src/main/java/jakarta/data/repository/DataRepository.java
api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Insert.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/PageableRepository.java
api/src/main/java/jakarta/data/repository/Param.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/jakarta/data/repository/Save.java
api/src/main/java/jakarta/data/repository/Update.java

Proofread and review the repository package JavaDoc.
I noticed we are inconsistently referring to the Id attribute as ID, id, and Id, sometimes all within the same class' JavaDoc.  Under this pull, I made them consistent, switching everything to Id, which matches the `@Id` entity annotation.
Documentation for Query and Param was sparse, so I added some.
I added code examples to those as well as to all of the built-in repository interfaces.
I have also added a brief first sentence (or revised an existing one for consistency) to appear on the package JavaDoc where it links to each class within the package.  The sentence indicates which are built-in repository interfaces, which are annotations, and where the annotations belong, along with the main purpose of the class.  This should help make …

review of the repository package JavaDoc

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/Sort.java
api/src/main/java/jakarta/data/page/Pageable.java
api/src/main/java/jakarta/data/page/Slice.java
api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Insert.java
api/src/main/java/jakarta/data/repository/Save.java
api/src/main/java/jakarta/data/repository/Update.java
tck/src/main/java/ee/jakarta/tck/data/common/cdi/Person.java

replaces the use of `@literal` with `@code`
There are also quite a few uses of `&#64;`, `&lt;`, `&gt;`, and just `<code>` that could be updated to use `@code` as well. I think this could improve readability in the javadocs, particularly cases like `module-info.java`, but it would be a large effort, so I would like to know what other people think before attempting it.

Replace @literal with @code in javadoc

---

spec/src/main/asciidoc/repository.asciidoc

The section on Entity Property Names applies across the spec and is not specific to Query by Method Name, so it should be moved from that section to the Entity Classes section.  Also, this section has implementation detail mixed in, which I'll replace with stating what the requirements are.

Entity Property Names section belongs under Entity Classes, not Query by Method Name

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/Box.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/Boxes.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Cover this test scenario from #133 
Use a repository that inherits from BasicRepository and defines no additional methods of its own. Use all of the built-in methods.
Fixes #133 because this is the last scenario that is listed there to add.

TCK tests for BasicRepository built-in methods

---

spec/src/main/asciidoc/chapters/license/license-efsl.adoc
spec/src/main/asciidoc/jakarta-data.adoc

Fixes #381 
Note: `{docyear}` is a generated variable by asciidoc and is parsed from `revdate`

Update copyright with real values

---

spec/src/main/asciidoc/chapters/introduction/project_team.adoc

Update the committer list in the spec doc according to the successful committer votes that just went through.  Note that the links won't resolve yet, but are very predictable and it is better to have the accurate list of names shown.  I also corrected the link to one of the exists names which had a copy/paste error that was pointing to a different person.

Update committer list

---

api/src/main/java/jakarta/data/repository/Repository.java

Some feedback that I received from attendees of JakartaOne is that they wanted better clarification of how to specify a non-default datasource for their repository that will work when using relational databases.  We already had the detail in the section, however, it was written in a way that didn't offer guarantees to the user.  This pull adds clarification.

Feedback from JakartaOne: clarify usage of Repository dataStore

---

spec/src/main/asciidoc/repository.asciidoc

This is a work in progress. Leaving it here so that people can post comments.

proposed rewrite of embeddables/associations

---

api/src/main/java/module-info.java

fixes #111 
Clarifies in the java doc that `Between` is inclusive of the parameters, matching what's in the spec (see repository.asciidoc)

Clarifying Between

---

api/src/main/java/jakarta/data/repository/Delete.java

- Update Delete annotation using void instead of the same instance once once the documentation does not show support to return the same interface.

Update Delete annotation return

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc

Fixes #405 by copying the list of precedence for interpreting repository methods from the JavaDoc to the specification document.

add precedence to specification document

---

api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Update.java

Fixes: 
https://github.com/jakartaee/data/issues/403

At Update annotation, should we be most restrict

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/ValidationTests.java

While running the TCK I found two errors that need to be fixed:
- The EntityTest application did not include the correct classes to run.
- The validation test repository used invalid query methods.

Fix TCK test errors

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/jakarta/data/repository/Delete.java

This covers the deleteAll() portion of issue #412 that Kyle raised.  The issue there is that the method signature of BasicRepository's deleteAll() method isn't a valid way to ask for deletion in Jakarta Data, so it doesn't work properly when the exact same method signature is copied to a user's custom repository that inherits from DataRepository, as Kyle did in his TCK test where he is aiming to add Jakarta Validation annotations to method signatures.
We can make deleteAll() valid under the Jakarta Data spec if we allow the `Delete` annotation to be used on a method without parameters and put it on BasicRepository's deleteAll(). Then when a user copies the method signature to their custom repository, it will behave as expected and perform a delete of all entities as intended.

allow Delete with no parameters to make BasicRepository.deleteAll() valid

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

While investigating other changes in the spec, I happened to notice that the TCK test testKeysetAwarePageOf7FromCursor is missing one of the Sorts.  The number of Sorts is supposed to exactly match the number of keyset values, but this test is providing 2 Sorts and 3 keyset values.  The 3 keyset values and their explanation in comments indicate that the test is intended to also sort on the numBitsRequired (in descending direction).  The test logic happens to otherwise be correct because this sort aligns with the descending sort on id that is also there.  In any case, we need to include the third sort so that the test matches up with spec requirements.

Missing Sort in TCK test

---

spec/src/main/asciidoc/chapters/introduction/project_team.adoc

Kyle's name is missing from the committer list in the spec.  It looks like all other names shown on https://projects.eclipse.org/projects/ee4j.data/who are present there.  I'm not sure how he was missed, but let's update it to include him.

Committer list is missing Kyle's name

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tck-challenge.yml
api/pom.xml
pom.xml
spec/pom.xml
tck-dist/pom.xml
tck/pom.xml

Reverts jakartaee/data#445
I'm going to disable that workflow for now until I can exclude the pom.xml updates.
see comment here: https://github.com/jakartaee/data/pull/445#issuecomment-1938850663

Revert "Update templates to include release 1.0.0-M3"

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tck-challenge.yml
.github/workflows/release.yml

The release workflow happens when a release is published and checks to make sure the tag for the release is added to the bug-report and tck-challenge templates.
I did not realize that when we preformed a checkout during this workflow that it would checkout using the context of the release.
Therefore, the bot would accidentally open a pull request to the main branch, including version updates to the latest release version. 
That should be fixed, but forcing the checkout action to use the main branch instead of the release branch.
Sorry for the confusion :)

Fix release workflow

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

It was discussed on today's Jakarta Data call to remove the built-in deleteAll method from BasicRepository.  Users could still write their own deleteAll if they wish, but this operation is seen as something that is not likely to be typically wanted.

Remove BasicRepository.deleteAll()

---

spec/src/main/asciidoc/jakarta-ee.adoc
spec/src/main/asciidoc/portability.asciidoc

I was not happy with section 7.1, so here's what I think it should say.
At least, something like this.
Thoughts?

rewrite section on Portability for Relational Databases

---

tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java

Missing `@Find` annotation in one of the TCK test repositories.

Fix error in validation tests

---

spec/src/main/asciidoc/jakarta-ee.adoc

Covers the first part of #473 to clarify language around transaction enlistment.

more precise wording around transaction enlistment

---

spec/src/main/asciidoc/jakarta-ee.adoc
spec/src/main/asciidoc/portability.asciidoc

If we're unable to reach consensus on #477, then we should just go ahead and slip support for Jakarta Persistence until a future version of Jakarta Data, hopefully after Jakarta Persistence itself starts to support a stateless programming model (a feature I proposed a while ago, but which did not make it into JPA 3.2).
This PR demonstrates that we can leave JPA support undefined in this release without doing any real violence to the spec as it exists today.

remove integration with Jakarta Persistence

---

.github/ISSUE_TEMPLATE/release.yml
CHANGELOG.adoc
README.adoc

- Update release template to use `draft` instead of `pre-release` during staging - FYI @lprimak
- I didn't realize pre-release signified "Non production ready" instead of "before release". 
- Also using `pre-release` will notify users that are following the repository so we should avoid using it until releases are publically available.
- Updated documentation files now that 1.0.0-M3 is publicly available 
Fixes #415

Update after release 1.0.0-M3

---

api/src/main/java/jakarta/data/Order.java

Since `Iterable` isn't at all convenient to work with in generated code.
Weird but true.

add Order.getSorts()

---

api/src/main/java/jakarta/data/Order.java

Wrapping with an unmodifiable list is unnecessary because the list is already guaranteed to be unmodifiable given that it comes from `List.of(...)`.  It looks like the code was lacking the necessary comments to make that clear, so I have added those in as well.

List was already unmodifiable

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

This pull removes the awkward BasicRepository.countBy method as discussed here, and updates the TCK,
> That brings up another, even simpler option. Just remove `countBy()` and don't replace it in version 1.0.
That would be great.
_Originally posted by @gavinking in https://github.com/jakartaee/data/issues/458#issuecomment-1964836766_

Remove BasicRepository.countBy

---

api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/metamodel/SortableAttribute.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiChar.java

It looks like I left off the the type parameter on `Attribute` like we have on `SortableAttribute`.  Although we currently got away with this because it doesn't create any `Sort<T>` instances, it is inconsistent and will be broken when the metamodel returns other typed things, such as if we want to enforce sending in only comparisons on a specific entity.

Attribute is missing type

---

api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Find.java
api/src/main/java/jakarta/data/repository/Insert.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Save.java
api/src/main/java/jakarta/data/repository/Update.java
spec/src/main/asciidoc/repository.asciidoc

See #488.
This pull request absolutely _does_ change semantics, eliminating:
- dangerous "quiet failure" which can easily lead to data corruption in the case of minor errors of program logic
- the previous "explosion" of acceptable method signatures which makes Jakarta Data more difficult to implement, while offering little additional flexibility to users
- nails down the treatment of optimistic lock acquisition failures
These changes make Jakarta Data significantly easier to implement, and lead users down a path where they are much less likely to accidentally write broken code.

fix requirements in Javadoc for built-in lifecycle annotations

---

api/src/main/java/jakarta/data/page/KeysetCursor.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/test/java/jakarta/data/page/KeysetPageRequestTest.java

Currently, `PageRequest.Cursor` is not even `Iterable`, which means that any time you want to read its elements you have to use an archaic indexed `for` loop. If you want to actually pass the key values as a list, you have to repackage them manually.
This adds an `elements()` method which automatically packages the elements as an unmodifiable list.

add Cursor.elements()

---

api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/Pagination.java

To allow to sorting by a member of a super-entity, most locations which accept `Sort<T>` should accept `Sort<? super T>`. This is important to do correctly now, since it would be a breaking change to fix it up later.

Replace Sort<T> by Sort<? super T> where appropriate

---

api/src/main/java/jakarta/data/repository/CrudRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

The requirements of the `Update` annotation are now in conflict with the requirements of the `CrudRepository` update methods, which are annotated with that annotation.  The `Update` annotation disallows the return types that these methods currently have and it has an opposite requirement for raising `OptimisticLockingFailureException` rather than indicating the non-matching condition in the method return value.  We will need to make `CrudRepository` align its own requirements to that of the `Update` annotation so that the spec doesn't contradict itself.  Also, I found another spot where the TCK is broken by the `Update` annotation changes.

CrudRepository update contradicts new lifecycle  method javadoc and TCK broken

---

api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/impl/KeysetAwarePageRecord.java
api/src/main/java/jakarta/data/page/impl/KeysetAwareSliceRecord.java
api/src/main/java/jakarta/data/page/impl/PageRecord.java
api/src/main/java/jakarta/data/page/impl/SliceRecord.java
api/src/main/java/module-info.java

This is, again, to ease the job of implementors.
I hope I got the semantics right here; please check!

similar to #485, add convenience impls of Page and Slice

---

api/src/main/java/jakarta/data/metamodel/impl/AttributeRecord.java
api/src/main/java/jakarta/data/metamodel/impl/SortableAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/impl/TextAttributeRecord.java
api/src/main/java/module-info.java

Rather than requiring that every implementation of Jakarta Data supply implementations of the metamodel interfaces (which are almost certainly going to be mutually isomorphic), I think it would be _really_ convenient if the Jakarta Data jar came with these three extremely trivial record types built in.
This is especially useful for those of us who have impls based 100% on code generation, and would prefer to avoid introducing a runtime support module.
WDYT?

add convenience implementations of metamodel types

---

api/src/main/java/module-info.java

I suspect that this sentence is not supposed to be there.
See #512.

remove an obsolete requirement

---

api/src/main/java/jakarta/data/repository/Find.java
api/src/main/java/module-info.java

rationalize the supported query return types

---

api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
api/src/main/java/jakarta/data/page/Page.java
api/src/main/java/jakarta/data/page/Slice.java
api/src/main/java/jakarta/data/page/impl/KeysetAwarePageRecord.java
api/src/main/java/jakarta/data/page/impl/KeysetAwareSliceRecord.java
api/src/main/java/jakarta/data/page/impl/PageRecord.java
api/src/main/java/jakarta/data/page/impl/SliceRecord.java

A `Page` always knows if there are more results. But the only way to really get that information is to call `page.nextPageRequest()`. Thus, the idiom for iteration is:
```java
Page<Book> page = library.books("%", pageRequest);
...
while (page.nextPageRequest() != null) {
page = library.books("%", slice.nextPageRequest());
...
}
```
which is quite nonbeautiful.
This proposal adds a `last()` method to `Page`, so that the idiom becomes:
```java
Page<Book> page = library.books("%", pageRequest);
...
while (!page.last()) {
page = library.books("%", slice.nextPageRequest());
...
}
```
Now, if it were my call I would also add:
- `last()` to `Slice`, not just `Page`, and
- `first()` to `KeysetAwareSlice`
but I wanted to see how you guys really react to just this.

add boolean Page.hasNextPage()

---

api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
spec/src/main/asciidoc/repository.asciidoc

fixes #508
Adds documentation to hopefully clarify that the combined sort criteria are used for the keyset cursor.
@gavinking please make suggestions to text if you have ideas to improve the wording.

clarify combined sort and keyset cursors

---

api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
api/src/main/java/jakarta/data/page/Slice.java
api/src/main/java/jakarta/data/page/impl/KeysetAwareSliceRecord.java
api/src/main/java/jakarta/data/page/impl/PageRecord.java
api/src/main/java/jakarta/data/page/impl/SliceRecord.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

This pull adds TCK coverage for hasNext and hasPrevious methods. (first commit)
And updates examples in the documentation to use hasNext before trying to obtain the next page request. (second commit)
Also, it eliminates the possibility of null page requests from nextPageable and previousPageable by raising NoSuchElementException (commit 3), which I think was intended to be part of the hasNext/hasPrevious solution and would allow us to cancel the pull that was going to wrap PageRequest with an Optional. If this part wasn't wanted, let me know and I can remove the third commit.

TCK coverage for hasNext and hasPrevious

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

TCK tests need to avoid using repository method return types like Iterable, LinkedList, ArrayList, and so forth which are no longer required by the Jakarta Data specification/JavaDoc.
This pull updates these TCK repository methods to switch to return types that the spec requires.
Also, there is a TCK test that was commented out due to having the Streamable return type, which was also removed. I switched this to use a return type of List, which is a return type that is required to be supported by the spec, and re-enabled that test after renaming it from testStreamable to something more appropriate.

TCK tests using return types that no longer correspond to spec requirements

---

api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/Pagination.java
api/src/test/java/jakarta/data/page/PageRequestTest.java
api/src/test/java/jakarta/data/page/PaginationTest.java

While I was bringing in the requestTotal updates, I spotted a bug where a value of `false` is lost when additional builder methods are invoked.  For example, if you write `PageRequest.ofSize(20).requestTotal(false).page(5)`, the `page` method reverts the requestTotal value back to its default of `true`.  This is happening because of a constructor in `Pagination` that defaults the value to `true` which all of these fluent builder-style methods are using rather than supplying the current value of requestTotal.  I added a unit test confirming this is broken, and fixed the issue by removing the extra constructor so that we force all methods to either explicitly supply or default the value as is done for all other record components.

requestTotal is lost when subsequent methods are invoked

---

api/src/main/java/jakarta/data/page/impl/PageRecord.java
api/src/main/java/module-info.java
api/src/test/java/jakarta/data/page/impl/PageRecordTest.java

I noticed this warning when building the project,
```
[WARNING] Javadoc Warnings
[WARNING] /Users/njr/lgit/data/api/src/main/java/jakarta/data/page/impl/PageRecord.java:42: warning: no comment
[WARNING] public PageRecord(PageRequest<T> pageRequest, List<T> content, long totalElements) {
[WARNING] ^
[WARNING] 1 warning
```
When I looked into correcting it by adding the missing JavaDoc, I realized the documentation would need to state how the constructor computes the moreResults record component and started to do so, but then realized the logic is incorrect for the path where the `totalElements` is unknown, always computing a `false` value for `moreResults`.  I added a unit test to demonstrate the error and corrected the code.
Also, I'm fixing a minor display issue in the return types table …

PageRecord computes incorrect moreResults when totalElements unknown

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/Sort.java
api/src/main/java/jakarta/data/exceptions/NonUniqueResultException.java
api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/module-info.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestDriver.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SignatureTestDriver.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SignatureTestDriverFactory.java

use {@code } everywhere

---

api/src/main/java/module-info.java

This is split off from the Query Language issue where it was identified that we lack documentation of what behavior to expect when sorting on enum attributes. I also noticed that our JavaDoc doesn't even tell users what the basic types are (including enums) so I have included that in the main JavaDoc and mentioned the behavior for enum sorting there.

enum ordering behavior is not documented

---

api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/PageRequestCursor.java
api/src/main/java/jakarta/data/page/Pagination.java
api/src/main/java/jakarta/data/page/impl/CursoredPageRecord.java
api/src/test/java/jakarta/data/page/KeysetPageRequestTest.java
api/src/test/java/jakarta/data/page/PaginationTest.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

migrate naming / terminology away from "keyset"

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/Sort.java
spec/src/main/asciidoc/repository.asciidoc

and re-dis-allow special parameters for repository methods returning a single entity.
This undoes the effect of 63686513.

roll back commit 63686513

---

README.adoc
api/src/main/java/module-info.java
spec/src/antlr/JDQL.g4
spec/src/main/asciidoc/jakarta-data.adoc
spec/src/main/asciidoc/query-language.asciidoc
spec/src/main/asciidoc/repository.asciidoc

Pushing this to collect feedback/suggestions in a disciplined way. Plenty of things still to clarify, of course.
See #458.

Initial specification of JDQL

---

api/src/main/java/jakarta/data/Order.java
spec/src/main/asciidoc/query-language.asciidoc
spec/src/main/asciidoc/repository.asciidoc

- add xrefs
- uniformity in capitalization and lifecycle vs life cycle
- clarify 4.10 to properly generalize precedence to cover provider-defined annotations
- clean up a code example that made JPQL look bad
- "criteria" is a plural noun

minor changes to chapter 4

---

api/src/main/java/jakarta/data/exceptions/OptimisticLockingFailureException.java
api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/jakarta/data/repository/CrudRepository.java
api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Insert.java
api/src/main/java/jakarta/data/repository/Save.java
api/src/main/java/jakarta/data/repository/Update.java
api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java

This is way more friendly to both users and implementors.
`Iterable` is an absolute PITA to work with, both for users, when a method returns `Iterable`, and for implementors, when a method accepts it. And there are no interesting types which implement `Iterable` but not `Collection`.
Now, I considered making the substitution `Iterable` -> `Collection`, but really all that allows is `Set`s. And here, in lifecycle methods, `Set` actually has the wrong semantics, because the returned values are correlated with input values by their order.
So `List` is really the right thing to use here!

change Iterable<E> to List<E> in lifecycle method signatures

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/jakarta/data/repository/By.java
api/src/main/java/jakarta/data/repository/Param.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/package-info.java
api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/CustomRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

These changes were included in PRs #551 and #553. I believe them to be uncontroversial. And since we're still discussing those other PRs, I have separated these changes out so that they are not blocked.

three minor changes

---

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

TCK tests that were using the Id alias for methods like `findByIdBetween` and their own custom `deleteById` method were broken by the removal of the Id alias from the spec. This pull updates them.

TCK tests broken by removal of alias for id

---

api/src/main/java/module-info.java

Jakarta Data still has one place that is referencing `jakarta.nosql.mapping.Entity`, which was moved to `jakarta.nosql.Entity`.

Correct reference to outdated nosql package name

---

spec/src/main/asciidoc/jakarta-ee.adoc

I messed up my asciidoc syntax: `&mdash;` doesn't work in the PDF.

fix broken emdashes in PDF output

---

api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiChar.java

As discussed on today's call, in the interest of quickly delivering compatible implementations, this PR removes a requirement on providers that we don't think is really that needed.

remove requirement that JD providers init user-written metamodel

---

pom.xml

We failed in the last deploys: https://ci.eclipse.org/data/job/jakarta-data-deploy/
I found out that it happens after upgrading the maven-gpg-plugin.
I will do the downgrade and rerun the build.

Downgrade the maven-gpg-plugin to 3.1.0

---

api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Param.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc

This was now very out of date, and I forgot about it in #520.
Also caught some more instances of 'run time' -> 'runtime', 'life cycle' -> 'lifecycle'.

Update the Javadoc of @Query after merge of JDQL

---

spec/src/main/asciidoc/repository.asciidoc

This aims to at least partially fix unclear specification language identified in #576 around the OrderBy keyword.

fix unclear spec doc for the OrderBy keyword

---

CHANGELOG.adoc
README.adoc

- Upgrade readme file
- Include query language at readme file
- update changelog file

Enhance Readme file

---

api/src/main/java/jakarta/data/repository/By.java

Since Lukas just merged my proposed change to JPQL which introduced `id()` and `version()` functions.

change '#id' to 'id(this)'

---

spec/src/antlr/JDQL.g4
spec/src/main/asciidoc/query-language.asciidoc
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add TCK tests for literals defined by the Jakarta Data Query Language.
While testing this, I noticed that we did not comply with [Jakarta Persistence 3.2 M2 specification]( https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2-m2#literals) regarding how enum literals and so I fixed that as well.

TCK tests for literals in query language

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

While investigating exceptions that are trapped in the TCK, I found a bunch of places where the TCK is trapping for `MappingException` that should have been updated when the specification was switched to `UnsupportedOperationException`. Fortunately, these are all cases where the requirement for the exception is at run time only because it requires finding out information from the database.  Otherwise we would have a problem testing the behavior at all in these cases.

TCK has outdated expectation for exception type

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add TCK tests for the `OR` operator, `NOT` operator, precedence for evaluating the `AND` operator ahead of the `OR` operator, and the use of parenthesis to control the order of evaluation.

TCK tests for boolean operators and parenthesis

---

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

With the addition of JDQL, it became optional for Jakarta Data providers that are backed by Jakarta Persistence to support JPQL, so TCK tests of `@Query` need to be updated to switch over to JDQL.  This pull converts the two remaining occurrences.

TCK must use JDQL rather than JPQL for Query

---

spec/src/main/asciidoc/query-language.asciidoc

and that it collapses the result set to one result

clarify that the type of "count(this)" is Long

---

api/pom.xml
pom.xml

Looking at #608, I don't see any usage of commons io in the data github repo. From git blame, it looks like this was brought along in the initial version of the pom.xml, and either usage was removed at some point or never existed.
Unless anyone know of another reason this is included I think we should remove it.

Remove commons-io Dependency

---

api/pom.xml
pom.xml

Same as #609, I think this has been around since the beginning and I don't see that it's used anywhere anymore.

Remove mockito dependency

---

api/pom.xml

We should compile the library with `-parameters`, to avoid seeing things like `arg0` in code generated from the built-in repository supertypes.
I don't use Maven, and so I don't know how to make this work, but we should do something like it.

compile with -parameters

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/Coordinate.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/MultipleEntityRepo.java

Add TCK tests for JDQL UPDATE and DELETE with and without a WHERE clause.
One of the tests uses a repository that handles multiple entity types where there is no primary entity type, relying on the FROM clause to identify the desired entity.  This also adds an additional entity to the TCK so that we can have some coverage for float, double, and UUID.

TCK tests for JDQL UPDATE and DELETE

---

api/src/main/java/jakarta/data/Order.java

These are convenience methods, but useful ones.

Add Order.by(List)

---

spec/src/main/asciidoc/repository.asciidoc

Since the TCK is now testing a variadic lifecycle method, we had better bless that in the spec.

clarify that variadic parameters are allowed for lifecycle methods

---

spec/src/main/asciidoc/repository.asciidoc

Previously, `@Query` accepted any sort of query language. Now it is defined to accept JDQL, which is more portable.

clarify portability of @Query

---

api/src/main/java/jakarta/data/page/impl/CursoredPageRecord.java

This wasn't completely obvious to me. Perhaps it should have been, but it wasn't.
Anyway, since it's possible to encapsulate it, we might as well.

add a constructor to CursoredPageRecord implementing an idiom from Nathan

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

The return type of these queries in JPQL is implicitly, by definitely, `List<Character>`, and Jakarta Data does not require conversion from `Character[]` to `char[]`.

char[] -> Character[] in TCK query method return type

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Recently, language was added to the spec which states:
> A superinterface of a repository interface must either:
>
> - be one of the built-in generic repository supertypes defined by this specification, `DataRepository`, `BasicRepository`, or `CrudRepository`, or
> - be a non-generic toplevel interface with no type parameters, whose abstract methods likewise declare no type parameters.
However, the TCK still has a test for a common superinterface that has a type parameter for the entity type.  I think this part of the TCK was written back when the primary entity type was the only possible entity that could be used by a repository.  In any case, it isn't valid anymore, and this pull updates the common superinterface into something that meets the above requirements.

TCK superinterface is no longer valid

---

spec/src/main/asciidoc/query-language.asciidoc

this is a traditional restriction on the 'order by' clause
see section 4.10 of latest JPA 3.2 specification

sync requirements for sorting with JPQL

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

This test, which was added yesterday, requires dynamically sorting by fields which are not `select`ed. As far as I know, the specification does not explicitly require this, and in traditional SQL, sorting by unselected fields is something that is not usually considered allowed, though it's true that many databases are quite forgiving here. 
Now, it's true that I didn't disallow this in JDQL, but there's a big difference between allowing it statically and allowing it for dynamically-added sorting. 
Actually I probably _should_ have disallowed it in JDQL, because in fact JPQL disallows it in section 4.10 of the latest Persistence spec. (Again, actually-existing JPQL implementations do allow it.) I will follow up with a PR that adds a caveat about this to section 5.5.5.
Folks, I think at …

remove a new test from TCK

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/repository.asciidoc

documentation is lacking for implied equals on Query by Method Name

---

api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/Sort.java

(`Order` and `Sort` cannot be combined with a `@Query` with an `order by` clause.)

make javadoc for Order and Sort consistent with spec

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java

There is no requirement in the spec that providers convert long to int in repository method parameters.

fix type of query by method name parameter in TCK test

---

spec/src/main/asciidoc/entity.asciidoc
spec/src/main/asciidoc/portability.asciidoc
spec/src/main/asciidoc/repository.asciidoc

That's in a different document now.

fix broken links to Query by Method Name

---

api/src/main/java/jakarta/data/page/Pagination.java
api/src/main/java/jakarta/data/repository/BasicRepository.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

This pull gets the TCK compiling again.
The first step was to add an Order parameter to BasicRepository.findAll(PageRequest) which cannot behave properly without a deterministic ordering.

TCK broken by #639

---

spec/src/main/asciidoc/repository.asciidoc

there was still a way to sneak in a generic repository method

plug a loophole in repository inheritance

---

tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/common/cdi/Directory.java
tck/src/main/java/ee/jakarta/tck/data/common/cdi/DirectoryRepository.java
tck/src/main/java/ee/jakarta/tck/data/common/cdi/PutTCKLifecyleMethod.java
tck/src/main/java/ee/jakarta/tck/data/core/cdi/ExtensionTests.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
tck/src/main/java/ee/jakarta/tck/data/web/cdi/ExtensionTests.java
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

- fixes #640 
- Verifies that another Jakarta Data Provider does not attempt to implement the Dictonary repository
- Fixes the Signature Tests
~DRAFT - signatures need to be updated with jakarta.data.spi package, but a compile time failure was merged.~

Fix QBN issue in CDI tests

---

.github/ISSUE_TEMPLATE/bug-report.yml
spec/pom.xml
spec/src/main/asciidoc/chapters/license/license-efsl.adoc

fixes #653
Sets the title for the html version of the new Extension file to:
`Jakarta Data: Query by Method Name Extension`
I had to switch the Specification to use a separate variable, to prevent the specification in the Extension file from using the doctitle.

Fixing subtitle for Extension html file

---

api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/Sort.java

These statements now make no sense, since a `PageRequest` can't carry sort criteria.

remove two obsolete sentences from jdoc

---

tck/src/main/java/ee/jakarta/tck/data/common/cdi/PersonEntity.java

#644 adds the requirement for custom entity defining annotations to be annotated with EntityDefining, but didn't update the one in the TCK.

EntityDefining was added without updating TCK

---

api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
api/src/main/java/jakarta/data/metamodel/package-info.java
spec/src/main/asciidoc/entity.asciidoc

I noticed this while reviewing the PageRequest/Sort decoupling, but it is not actually related so I opened a separate PR for it.
The examples we give for static metamodel classes in the javadoc have some bad practices.  In one example, we are initializing all the fields and unnecessarily marking them `volatile` rather than `final`, which results in unsafe code that could accidentally be overwritten at run time with no benefit. I don't want anyone copy/pasting from that - either when they write an annotation processor or for direct use.
In another example, we aren't even using our own constants: `new SortableAttributeRecord&lt;&gt;("ssn");`
We already defined an `SSN` constant for the `"ssn"` value only a few lines above, and we should be using it here.
Also, these could be a lot cleaner …

Static metamodel examples show bad coding practices

---

api/src/main/java/module-info.java

Updates an example method name used in JavaDoc because `findNamed` is not a valid method name for Query by Method Name.

Fix invalid method name in JavaDoc

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/method-query.asciidoc
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbersPopulator.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/ValidationTests.java

In light of #657 I took a close look at this and I propose the following improvements:
1. only `find` queries can have sorting
2. introduce `All` keyword to allow queries with no restriction, resolving #657
3. simplify `OrderBy` to disallow "weird" things
4. rewrite the grammar using a more readable (ANTLR-style) syntax

improvements to Query by Method Name grammar

---

api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/package-info.java
api/src/main/java/jakarta/data/repository/BasicRepository.java
api/src/main/java/module-info.java

Another pull to fix example code that was broken by PageRequest/Sort decoupling.
and I also spotted a few places where we have bad example code that isn't allowing for a consistent ordering when using pagination.

Fix more javadoc broken by the PageRequest/Sort decoupling

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

give cursor TCK tests a meaningful page number rather than defaulting to 1

---

api/src/main/java/jakarta/data/Order.java
api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/page/Page.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/Pagination.java
api/src/main/java/jakarta/data/page/impl/CursoredPageRecord.java
api/src/main/java/jakarta/data/page/impl/PageRecord.java
api/src/test/java/jakarta/data/page/PageRequestCursorTest.java
api/src/test/java/jakarta/data/page/PageRequestTest.java
api/src/test/java/jakarta/data/page/PaginationTest.java
spec/src/main/asciidoc/repository.asciidoc
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

fixes #672
This adds onto the change to remove next()/previous() (first commit) and also removes page(number) from PageRequest (second commit).  All of these methods can mislead applications into writing code that causes wrong behavior.

PageRequest.page(num) method can cause wrong usage

---

api/src/main/java/jakarta/data/page/PageRequestCursor.java
api/src/main/java/jakarta/data/page/Pagination.java
api/src/test/java/jakarta/data/page/PageRequestCursorTest.java

toString of both Pagination (PageRequest) and PageRequestCursor (Cursor) both output a string that says the cursor has X number of keys. This is inaccurate. There is only one key, which is formed by all of the values.  This PR makes corrections to the toString output.

PageRequest toString wrongly states a cursor has multiple keys

---

spec/src/main/asciidoc/method-query.asciidoc

There should be no semantic changes here.

more improvements to the presentation of the QbMN feature

---

pom.xml
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestDriver.java

Address signature test issues from issue 681

---

spec/src/main/asciidoc/repository.asciidoc

instead of Query by Method Name, which has been exiled to a separate document.

use @Query and @Find for example code in chapter 4

---

api/src/main/java/module-info.java

The javadoc needs a few updates to align with the recent grammar changes that made `By` optional and disallowed its use in the absence of any conditions (for example, `deleteBy()`). Also, it looks like the javadoc doesn't make any mention of the ability to place ignored text in certain parts of the method name.  This PR attempts to get the javadoc more lined up with the grammar and the description of it within the specification document.  There should be no changes to specification requirements in this PR, only making the javadoc consistent with what the specification already requires.

JavaDoc needs to align with recent changes to method name grammar

---

api/src/main/java/jakarta/data/page/CursoredPage.java
spec/src/main/asciidoc/repository.asciidoc

I should have spotted these code examples in spec/javadoc that need updating due to the replacement of the PageRequest.beforeKey and afterKey methods, but somehow missed them. These methods don't exist anymore and should be switched over to the beforeCursor/afterCursor methods. Also, I added a page number to these examples to match up with updates that Gavin wanted to a TCK test when requesting a middle page with cursor pagination.

beforeKey and afterKey were missed in some examples

---

api/src/main/java/jakarta/data/repository/Find.java
api/src/main/java/jakarta/data/repository/Query.java

The TCK tests that this exception is thrown, but it was never mentioned in the spec or in the Javadoc.

mention EmptyResultException in Javadoc for @Find and @Query

---

pom.xml
tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc
tck-dist/src/main/asciidoc/sections/04prereq.adoc
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21

Upgrade to 2.3 signature test plugin

---

spec/src/main/asciidoc/repository.asciidoc

The `@By` annotation accepts strings.

fix bug in example using static metamodel

---

tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Product.java

Jakarta Data repositories are stateless, and Jakarta Data entities are unmanaged objects, and thus lazy fetching is impossible.
However the TCK makes use of it at line 77 of `PersistenceTests`.
I have fixed this issue by changing the mapping of the `@ElementCollection` to `EAGER`.

change collection in TCK to use fetch=EAGER

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

If #599 goes in, here is a TCK test to cover ID(THIS) in various clauses where it is allowed.

TCK test for ID(THIS)

---

api/src/main/java/module-info.java
spec/src/main/asciidoc/method-query.asciidoc
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharactersPopulator.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/CustomRepository.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/NoSQLEntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java

limit countBy methods to return long instead of int

---

tck-dist/src/main/asciidoc/sections/07.1se-mode.adoc
tck-dist/src/main/asciidoc/sections/07.2ee-mode.adoc
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Standalone.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/StandaloneExtension.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestProperty.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestPropertyUtility.java

Fixes #700 
- Updates TCK Dist docs to better explain the difference between `<groups>` and `<jakarta.tck.profile>` settings
- The TCK Dist doc said jakarta.tck.profile was optional, but the TCK would throw an error if it was not set.
- Fixed the TCK to no longer throw an error when unset
@starksm64 - this fixes the issue you opened.
However, seeing as how the main purpose of `jakarta.tck.profile` is to determine if we need to run in standalone mode or not, would it be better to instead have a boolean property `jakarta.tck.standalone` that can be true or false to control this mode? 
This would help reduce the overlapping confusion between `groups` and `jakarta.tck.profile` (the `groups` configuration is not available to us at test time which is why we require a seperate property)
If so, …

Fix required property jakarta.tck.profile

---

.github/ISSUE_TEMPLATE/certification.yml
.github/ISSUE_TEMPLATE/release.yml
.github/workflows/specification.yml
api/pom.xml
api/src/main/javadoc/doc-files/speclicense.html
spec/pom.xml
spec/src/main/asciidoc/chapters/license/license-efsl.adoc
tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc
tck-dist/src/main/asciidoc/sections/09running.adoc
tck-dist/src/main/java/ee/jakarta/tck/data/metadata/CollectMetaData.java

Here are a list of things I got called out for when doing the Concurrency Release Review.
Figured I'd get them fixed in Data before the we open up a Release Review: 
- Update certification doc to eliminate confusion on what SHA Checksum to use TCK Dist zip vs TCK jar
- Generated spec docs need only major/minor versions (1.0) vs (1.0.0)
- Update EFSL license to version 1.1
- Test counts in TCK documentation can be confusing.

Updates needed for release review

---

spec/src/main/asciidoc/query-language.asciidoc

I put a tiny detail where we explicitly say that the parameter starts with one instead of zero.

Clarifies the order and avoid the vendor start with One instead of Zero

---

spec/src/main/asciidoc/query-language.asciidoc

Include a note about no mix types of query in a single one

---

README.adoc

Enhance documentation readme file

---

.github/dependabot.yml
tck-dist/pom.xml
tck-dist/src/main/artifacts/artifact-install.sh
tck-dist/src/main/asciidoc/sections/05inventory.adoc
tck-dist/src/main/asciidoc/sections/08example-runner.adoc
tck-dist/src/main/asciidoc/sections/10signature.adoc
tck-dist/src/main/assembly/assembly.xml
tck-dist/src/main/pom.xml
tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml

Fixes #737 
FYI @edburns @lukasj
Tested dependabot in my fork and it worked:

Fix concerns with tck-dist

---

tck-dist/src/main/asciidoc/sections/01preface.adoc
tck-dist/src/main/asciidoc/sections/05inventory.adoc
tck-dist/src/main/asciidoc/sections/07.1se-mode.adoc
tck-dist/src/main/asciidoc/sections/07.2ee-mode.adoc
tck-dist/src/main/asciidoc/sections/09running.adoc
tck-dist/src/main/java/ee/jakarta/tck/data/metadata/CollectMetaData.java
tck-dist/src/main/starter/ee-pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Core.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Platform.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Standalone.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Web.java
tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/StandaloneExtension.java

Swap full > platform

---

tck-dist/pom.xml
tck-dist/src/main/pom.xml
tck/pom.xml
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/DatabaseType.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestProperty.java
tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestPropertyHandler.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/signature/SignatureTests.java

Fixes #768 
- Added two new properties:
- jakarta.tck.database.type - So that we can write test logic based on database type, such as, column or graph
- jakarta.tck.database.name - so that we can write test logic based on database name, such as, oracle or mongo
- This is for future consideration and currently isn't used. 
- Fixed some spacing issues
- Only read system properties once instead of every time they are used.

Verify behavior based on Database type

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Per @otaviojava 's comment in https://github.com/jakartaee/data/pull/771/files#r1649951754 , Key-Value databases are not capable of GreaterThan, GreaterThanEqual, LessThan, and LessThanEqual, whereas other database types are able to perform them.  This PR updates TCK tests accordingly.
Additional TCK updates are also needed per the table, but this PR is only attempting to address this subset. 
Even with just this subset, I can already see that a large amount of test coverage is lost, so in the future there will also need to be an effort to ensure the TCK has coverage for various aspects of the spec in terms of capability that is possible for all database types.  We did ask for all of this sort of NoSQL database capability information before starting to write the TCK so that it could be …

TCK cannot require GT, GTE, LT, LTE for Key-Value databases

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/web/validation/ValidationTests.java

TCK cannot require And, Or, In, and sorting for some types of NoSQL databases.
Per table from Otavio's comment in:
https://github.com/jakartaee/data/pull/771#discussion_r1649951754

limitations on sorting and In, Or, And keywords

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

While working with parenthesis with Graph is true, we cannot confirm it with the document database.
Some document databases that don't support parenthesis:
- MongoDB 
- CouchDB
- RethinkDB
- Amazon DocumentDB
- Firebase Firestore

Increase the value to work with parenthesis

---

CONTRIBUTING.adoc

- After seeing the first contribution of a newcomer, I could see that we are missing some guides and information for new contributions. This PR works to fix it, enhance the documentation and explain more about the legal part and the commit message [using convention](https://www.conventionalcommits.org/en/v1.0.0/)

Enhance contribuiting documentation

---

tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Unlike relational databases, which consistently return the number of affected records, many NoSQL databases, especially those with eventual consistency, do not guarantee this behavior. This PR addresses the issue by disabling the return of affected record counts for NoSQL operations, opting for zero or a consistent placeholder value instead. This ensures compatibility and prevents problems due to unreliable count data in systems like Couchbase, Elasticsearch, Cassandra, and Redis.
By adopting this change, the application will handle updates and deletes uniformly across different NoSQL databases, avoiding problems associated with inconsistent or unavailable record counts.

Disable Return of Affected Records Count for Update and Delete Operations in NoSQL Databases

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumber.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbersPopulator.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Fixes #830
This corrects the error in the TCK where it expects sorting on an enum attribute to be done in a particular way, which [per the spec is vendor specific](https://github.com/jakartaee/data/issues/830#issuecomment-2308476456).
Because this fix is needed in the 1.0.1 maintenance release, it should be as minimal as possible to fix the TCK, which is achieved by adding an entity attribute for the ordinal value and switching a few places in the TCK to sort on that value instead of the enum.

TCK cannot expect sorting on enum

---

api/src/main/java/jakarta/data/repository/OrderBy.java

I noticed the class javadoc for `@OrderBy` doesn't mention or show an example of the `descending` property. I'm not sure if it's the case for other IDE's but in VSCode, the javadoc shown when hovering over an annotation doesn't include the properties, so without a description in the class javadoc, the availability of the `descending` property may not be obvious.

Adding sample of descending property to OrderBy Javadoc

---

api/src/main/java/jakarta/data/repository/By.java

An example in the By annotation Javadoc ought to be using a return type that can handle multiple results because the query can product multiple results.

Javadoc example for By annotation has return type that does not make sense

---

api/src/main/java/module-info.java

Javadoc has a section about pagination which has an example method
```
* Product[] findByNameLike(String pattern, PageRequest pageRequest, Order&lt;Product&gt; order);
```
that is supposed to be used for the following example usage pattern,
```
* page1 = products.findByNameLikeAndPriceBetween(
*                 namePattern, minPrice, maxPrice, page1Request,
*                 Order.by(Sort.desc("price"), Sort.asc("id"));
```
The two are inconsistent. The methods have different names and accept a different number of parameters.
This PR updates them to match so that the example will make more sense.

Inconsistent method signature in pagination example

---

.github/workflows/specification.yml
pom.xml
tck/pom.xml

- Output directory of apidocs was switched from `/target/` to `/target/reports/` as of maven-javadoc-plugin:3.10.0
- Remove maven-javadoc-plugin from parent pom and let each module decide if it creates javadoc
- Update the tck module to use the same version of the maven-javadoc-plugin plugin as the api module to avoid errors

Update useage of maven-javadoc-plugin

---

api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/module-info.java

While reading the section, "Parameter-based automatic query methods", in the module-info Javadoc, I noticed the section is a little bit misleading because it only mentions `@Find` being used to indicate automatic query methods. However, `@Delete` can also be used for automatic query methods (determined by the absence of an entity typed method parameter), as indicated by the `@Delete` Javadoc.  This PR clarifies the module-info Javadoc to acknowledge this, also clarifying that the special parameter types like PageRequest that it says you can use with automatic query methods are specifically for use with the `@Find` annotation, not `@Delete`.  There is no change in behavior or requirements here, only making this section of the module-info JavaDoc clear and consistent with the rest of the …

Javadoc description of automatic query methods is incomplete

---

api/src/main/java/jakarta/data/event/LifecycleEvent.java
api/src/main/java/jakarta/data/event/PostDeleteEvent.java
api/src/main/java/jakarta/data/event/PostInsertEvent.java
api/src/main/java/jakarta/data/event/PostUpdateEvent.java
api/src/main/java/jakarta/data/event/PreDeleteEvent.java
api/src/main/java/jakarta/data/event/PreInsertEvent.java
api/src/main/java/jakarta/data/event/PreUpdateEvent.java
api/src/main/java/jakarta/data/repository/Delete.java
api/src/main/java/jakarta/data/repository/Insert.java
api/src/main/java/jakarta/data/repository/Update.java
spec/src/main/asciidoc/jakarta-ee.adoc

See #373. [Note that the first to propose this was @hantsy.]
Here's a rough and fairly minimal idea for what this could look like. 
Note that here there is an `Event` class for each kind of event, instead of a single `LifecycleEvent` with `@Before @Update` and `@After @Insert` qualifiers on the observer side. The reason for this is that we don't have a dependency on CDI, so I can't use the `@Qualifier` annotation to declare event qualifier types.
An event observer would look like:
```java
void afterUpdate(@Observes PostUpdateEvent<Book> event) { ... }
```
~I would love to be able to filter by entity type, but I don't think CDI allows filtering events by type argument. (At least it didn't in 1.0, though that was a long time ago.)~
~As a workaround for that, we could have `@Before @Update …

first rough proposal for events

---

api/src/main/java/jakarta/data/repository/BasicRepository.java
spec/src/antlr/JDQL.g4
spec/src/main/asciidoc/query-language.asciidoc

A proposal, in case we want this in 1.0.

fully incorporate id(this) into JDQL

---

api/src/main/java/jakarta/data/BasicRestriction.java
api/src/main/java/jakarta/data/BasicRestrictionRecord.java
api/src/main/java/jakarta/data/CompositeRestriction.java
api/src/main/java/jakarta/data/CompositeRestrictionRecord.java
api/src/main/java/jakarta/data/Operator.java
api/src/main/java/jakarta/data/Restrict.java
api/src/main/java/jakarta/data/Restriction.java
api/src/main/java/jakarta/data/TextRestriction.java
api/src/main/java/jakarta/data/TextRestrictionRecord.java
api/src/test/java/jakarta/data/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/CompositeRestrictionRecordTest.java
api/src/test/java/jakarta/data/RestrictTest.java
api/src/test/java/jakarta/data/TextRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java
api/src/test/java/jakarta/data/metamodel/SortableAttributeTest.java
api/src/test/java/jakarta/data/metamodel/TextAttributeTest.java

If I remember the discussion correctly, the 3 ideas for how to do negation of restrictions were:
- restriction.negate()
- Restrict.not(restriction)
- Restrict.notAll(restrictions) / Restrict.notAny(restrictions)
notAll/notAny seemed the most awkward to me, and I realized that the first two are basically the same thing, and it would be trivial to have both ways, where Restrict.not(restriction) is a convenience method that invokes restriction.negate().

negated restrictions

---

api/src/main/java/jakarta/data/BasicRestriction.java
api/src/main/java/jakarta/data/BasicRestrictionRecord.java
api/src/main/java/jakarta/data/Restrict.java
api/src/main/java/jakarta/data/TextRestrictionRecord.java
api/src/test/java/jakarta/data/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/RestrictTest.java
api/src/test/java/jakarta/data/TextRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java
api/src/test/java/jakarta/data/metamodel/SortableAttributeTest.java
api/src/test/java/jakarta/data/metamodel/TextAttributeTest.java

Update the restrictions API to align with the decision made under #906 to use the term "attribute" for entity attributes/fields/properties.
This PR does not cover updating the rest of the spec or javadoc that was already written prior to v1.1.

update Restrictions to standardize on attribute terminology

---

api/pom.xml

Fixes #956
Adds an OSGi manifest to the API JAR, for easier use within OSGi runtimes.
Inspiration taken from:
* https://github.com/jakartaee/expression-language/blob/6.0.1-RELEASE-api/api/pom.xml#L184-L214
* https://github.com/jakartaee/persistence/blob/3.2-3.2.0-RELEASE/api/pom.xml#L284-L309

Generate OSGi Manifest for API

---

api/src/main/java/jakarta/data/metamodel/restrict/EmptyRestriction.java
api/src/main/java/jakarta/data/metamodel/restrict/Restrict.java
api/src/main/java/jakarta/data/metamodel/restrict/Unmatchable.java
api/src/main/java/jakarta/data/metamodel/restrict/Unrestricted.java
api/src/test/java/jakarta/data/metamodel/restrict/RestrictTest.java

This came up during discussion of one of the other issues.
Given a repository method that allows Restrictions to be supplied at run time, such as,
```
@Find
List<Person> bornIn(int year, Restriction<Person> restrictions, Order<Person> order);
```
There is currently no way for a repository user to use the method when a case arises where they don't need to make any additional restrictions.
Currently, allowing for that possibility would require the repository to duplicate the method and omit the Restriction parameter,
```
@Find
List<Person> bornIn(int year, Order<Person> order);
```
One idea to avoid the need to duplicate repository methods is to allow an empty Restriction instance that indicates the decision to not apply any additional restrictions,
```
everyoneBornIn2000 = …
```

Need a way to indicate no additional restrictions

---

api/src/main/java/jakarta/data/metamodel/restrict/BasicRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/CompositeRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/TextRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/Unmatchable.java
api/src/main/java/jakarta/data/metamodel/restrict/Unrestricted.java
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/CompositeRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/TextRestrictionRecordTest.java

Adds implementation of toString on the built-in Restrictions to display in a concise way that is meaningful.
For example,
`name LIKE "Jakarta EE %"`
Or,
`ALL (price GREATER_THAN_EQUAL 50, price LESS_THAN 100)`

implement toString to make Restrictions more readable

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NumberInfo.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_NaturalNumber.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add test scenarios for various return types with a Java record where the record component names match entity attribute names and are used to request the retrieval of a subset of entity attributes.
This does not cover any scenarios that require the annotation to identify the entity attribute name(s). Separate PRs will be needed for those scenarios.

TCK tests of record result types where record component names match the entity attributes

---

api/src/main/java/jakarta/data/page/PageRequest.java

Accommodate NoSQL databases that are incapable of page totals by clarifying that the request for totals can be deferred until they are asked for, and prepare the user for the possibility of an exception to be raised at that time rather than immediately upon supplying the PageRequest with requestTotals to a repository method.
This goes along with Otavio's #963 where we are trying to figure out a compatible way for NoSQL databases that aren't capable of retrieving totals to be usable for PageRequest instances that by default do not set withoutTotals.

Allow NoSQL to defer request for totals and raise UnsupportedOperationException later

---

api/src/main/java/jakarta/data/metamodel/BasicAttribute.java
api/src/main/java/jakarta/data/metamodel/TextAttribute.java
api/src/main/java/jakarta/data/metamodel/restrict/BasicRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/Restrict.java
api/src/main/java/jakarta/data/metamodel/restrict/UnaryOperator.java
api/src/main/java/jakarta/data/metamodel/restrict/UnaryRestriction.java
api/src/main/java/jakarta/data/metamodel/restrict/UnaryRestrictionRecord.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java

This makes the following changes:
1. Introduces `UnaryRestriction` and `UnaryOperator` to represent `is null` and `is not null`.
2. Disallows `null` as a value in `BasicRestriction`, since the meaning of `= null` and `<> null` varies between datastores.

fix up treatment of null restrictions

---

api/src/main/java/jakarta/data/metamodel/restrict/BasicRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/CompositeRestriction.java
api/src/main/java/jakarta/data/metamodel/restrict/CompositeRestrictionRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/Operator.java
api/src/main/java/jakarta/data/metamodel/restrict/TextRestrictionRecord.java
api/src/main/resources/rules.xml
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/CompositeRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/TextRestrictionRecordTest.java

Address this review comment from #962
> `ALL (price GREATER_THAN_EQUAL 50, price LESS_THAN 100)`
Why not align the `toString()`s with the equivalent JDQL, so:
```hql
(price >= 50 AND price < 100)
```
_Originally posted by @gavinking in https://github.com/jakartaee/data/issues/962#issuecomment-2640902362_

address review comment to format Restriction toString more like JDQL

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/WholeNumber.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add TCK tests returning Page/List/Optional/array of record where the record component names do no match the entity attribute names, and the annotation is used to identify the corresponding entity attributes.

TCK test of record result types where the repository method uses Select to identify the entity attributes because record component names do not match

---

api/src/main/java/jakarta/data/repository/Find.java

A typo caused the value member of the Find annotation to be a constant rather than a member of the annotation. This PR corrects it.

Find value should be annotation member, not a constant

---

tck-dist/src/main/starter/ee-pom.xml
tck-dist/src/main/starter/se-pom.xml
tck/pom.xml

junit-platform-launcher is no longer a transitive dependency of junit-jupiter and will cause Arquillian to fail to discover tests at runtime when missing.

fix: add junit-platform-launcher

---

spec/src/main/asciidoc/repository.asciidoc

because the document structure was broken

add needed spaces at end of file

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/MultipleEntityRepo.java

This PR has TCK tests for
* selecting a single attribute of entities as `long[]`, `Optional`, and `Page`, where the entity is unspecified and defaults to the primary entity type of the repository.
* selecting a single attribute of entities as `int`, `List`, and `Stream`, where the entity is chosen by the `Find` annotation value.

TCK tests of selecting one attribute of entities, where entity is determined by Find value or primary entity type

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/HexInfo.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

Add TCK tests where a Find method uses the Find.value() to specify the entity class to query for, with results returned as records that are subsets of the entity. In some tests, the record component names match the entity attribute names, and in another test they do not matching, requiring the repository method to use Select to specify the entity attributes.

TCK tests Find(entityclass) to disambiguate which entity to select values from when returning a record

---

tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/CardinalNumber.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java

TCK tests that of repository methods that return a subset of entity attributes as a Java record, where the record component uses the Select annotation to identify a corresponding entity attribute.  Some of the tests also include specifying the Find annotation value to identify the entity.  Others assume the primary entity type.

TCK tests of Select annotation on record component to identify the entity attribute

---

api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/module-info.java

This PR includes the following:
Fixes a mistake where an entity class name in an example doesn't match the example code where it is used.
The javadoc overview on methods returning Java records is specific to `@Find`. It should also allow for `@Query`.
An idea for a more concise for of `@Query` returning Java records, where the `SELECT` clause can be omitted entirely if the record component names match.
The latter is done as its own commit so that it could be removed from the PR in case it turns out to be unwanted for some reason.  Let me know.

Fix typo, include example Query with SELECT returning record, and idea for more concise usage

---

api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/module-info.java

While looking up some information on pagination, I noticed that our main examples to users on how to use pagination have repository methods returning an array rather than a `Page`.  It is valid to return an array, except not for the example, which won't compile because it shows `Page.content()` being subsequently invoked on the array return value, and then again later on.  This needs to be corrected, preferably by returning `Page` instead.

Pagination examples should encourage use of Page rather than array

---

api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/page/Pagination.java

Does anyone remember if there was a good reason that `PageRequest` doesn't offer the ability to mutate the page number?
Because to me it feels much more natural to write `Page.ofSize(PAGE_SIZE).page(pageNumber)` than `Page.ofPage(pageNumber).size(PAGE_SIZE)`.

add PageRequest.page(long)

---

api/src/main/java/jakarta/data/repository/Select.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java

This is an idea for a possible improvement to `@Select` that will switch its `value` from an array to a single item to prevent the following which do not make sense:
- `@Select({ "attributeName1", "attributeName2", ... })` on a single record component
- `@Select({})`
The only place where we need multiple entity attribute names is on a repository method, and so this PR proposes to make the annotation repeatable (as we have for `OrderBy`) on a method,
```
@Repeatable(Select.List.class)
```
```
@Target(ElementType.METHOD) // RECORD_COMPONENT is intentionally omitted
@interface List {
```
See the updated TCK tests for examples of usage.
It's a little bit more to type when specified on a method that returns a record. However, it does format nicely and has consistency with existing usage of …

Disallow multiple Select values on a record component

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/repository/Find.java
api/src/main/java/jakarta/data/repository/First.java
api/src/main/java/jakarta/data/repository/Query.java
api/src/main/java/jakarta/data/repository/Select.java
spec/src/main/asciidoc/repository.asciidoc

introduce First annotation

---

api/src/main/java/jakarta/data/exceptions/NonUniqueResultException.java
api/src/main/java/module-info.java

Javadoc should point to the `@First` annotation as a solution to `NonUniqueResultException` rather than `Limit.of(1)`, which relies on the user of the method to always supply a `1` value.
Also, our main Javadoc starting page that highlights available spec function should mention `@First` and include an example of it.  That page also has a side-by-side comparison of a parameter-based find method vs a Query by Method Name find method and it would be nice to include `@First` there as well now that we have an alternative to the Query by Method Name `findFirst#By` name pattern.

javadoc should point to the First annotation as a solution to NonUniqueResultException

---

api/src/main/java/jakarta/data/metamodel/constraint/Constraint.java

Fixed:
- missing like()
- inconsistent return types
- direct use of impl classes
- order of methods
Actually I'm not even sure we really need these methods anymore, but I suppose they're more easily discoverable.

clean up the factory methods on Constraint

---

api/src/main/java/jakarta/data/metamodel/Attribute.java

Fixes the compile failure in the TCK by fixing the breaking change from Attribute.declaringType

Fix breaking change with declaringType()

---

api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/metamodel/ComparableAttribute.java
api/src/main/java/jakarta/data/metamodel/NavigableAttribute.java
api/src/main/java/jakarta/data/metamodel/NumericAttribute.java
api/src/main/java/jakarta/data/metamodel/SortableAttribute.java
api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
api/src/main/java/jakarta/data/metamodel/package-info.java
spec/src/main/asciidoc/entity.asciidoc

Similar to how we updated examples and recommended usage to prefer ComparableAttribute over SortableAttribute, we should do likewise for preferring NumericAttribute over either of these, and for NavigableAttribute over BasicAttribute.
This also includes doc updates for these new attribute types as we did when introducing ComparableAttribute.  It does not include any documentation for Expression, Restriction, Constraint, and other completely new classes in the static metamodel which are still being worked with. The reasoning is that Attribute already exists and can be expected to be more stable, but these others are still changing and not certain enough yet to proceed with devoting effort to adding the documentation at this point.

Prefer NumericAttribute over ComparableAttribute and SortableAttribute

---

api/src/main/java/jakarta/data/metamodel/path/ComparablePathRecord.java
api/src/main/java/jakarta/data/metamodel/path/NavigablePathRecord.java
api/src/main/java/jakarta/data/metamodel/path/NumericPathRecord.java
api/src/main/java/jakarta/data/metamodel/path/TextPathRecord.java

The `XxxxPathRecord` doesn't need to directly implement `XxxxExpression`, because `XxxxPath` already does.

remove duplicated 'implements' from PathRecords

---

api/src/test/java/jakarta/data/metamodel/expression/ExpressionTest.java
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/TextRestrictionRecordTest.java
api/src/test/java/jakarta/data/mock/entity/Book.java
api/src/test/java/jakarta/data/mock/entity/_Book.java

This PR moves the Book entity and static metamodel class to a common location where unit tests can share it (first commit) and then adds the first two unit tests to try out Expressions and ensure they are capturing the information that will be needed to construct a query.

First unit tests to experiment with expressions

---

api/src/main/java/jakarta/data/metamodel/Attribute.java

Address review comment from @otaviojava to include a message on the UnsupportedOperationException that is raised by Attribute.declaringType()

message for unsupported exception on declaringType

---

api/src/main/java/jakarta/data/metamodel/constraint/BetweenRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/EqualToRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/GreaterThanOrEqualRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/GreaterThanRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/InRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/LessThanOrEqualRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/LessThanRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/LikeRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/NullRecord.java

Some of our Constraint records implement .equals and hashCode methods while others are letting it default to what you get automatically for Java records.  These should all be consistent, and I don't see an reasons why we need to override it, so the approach I took in this PR is to remove it where we had it implemented.  If anyone does know of a reason why we need to override it or why an implementation we provide is better, we could go the other direction and add it where currently missing instead.

Let Java record provide the equals and hashCode implementation

---

api/src/main/java/jakarta/data/metamodel/restrict/BasicRestriction.java
api/src/main/java/jakarta/data/metamodel/restrict/BasicRestrictionRecord.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java
api/src/test/java/jakarta/data/metamodel/ComparableAttributeTest.java
api/src/test/java/jakarta/data/metamodel/SortableAttributeTest.java
api/src/test/java/jakarta/data/metamodel/TextAttributeTest.java
api/src/test/java/jakarta/data/metamodel/expression/ExpressionTest.java
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java
api/src/test/java/jakarta/data/metamodel/restrict/RestrictTest.java
api/src/test/java/jakarta/data/metamodel/restrict/TextRestrictionRecordTest.java

BasicRestriction has a method, `attribute()`, that returns `String`, which is possibly the name of an entity attribute and otherwise `null`.  This is kind of awkward and is actually unnecessary because whenever the entity attribute name is available, then the `.expression()` is also an instance of `Attribute` which has `.name()` to get the entity attribute name. So we can omit the `attribute()` method entirely and not need to deal with the `null` at all, which seems preferable.
Also, under this PR, I noticed that we have a unit test case called SortableAttributeTest, but it tests ComparableAttribute rather than SortableAttribute, so I renamed it to better reflect what it covers.

Remove .attribute() from BasicRestriction

---

api/src/main/java/jakarta/data/metamodel/constraint/Like.java
api/src/main/java/jakarta/data/metamodel/constraint/LikeRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/NotLike.java
api/src/main/java/jakarta/data/metamodel/constraint/NotLikeRecord.java

I had decided that `Like.literal()` was unnecessary, but now I've realized there are still cases for it, for example if I have a repo method declared like this:
```java
@Find List<Books> books(Like title);
```
It's useful to be able to call it with:
```java
var books = library.books(Like.literal("Hibernate in Action"));
```
Incidentally, I noticed that `Like` and `NotLike` had superficially divergent implementations.

Add Like.literal() and sync implementations of Like and NotLike

---

api/src/main/java/jakarta/data/metamodel/Expression.java
api/src/main/java/jakarta/data/metamodel/constraint/In.java
api/src/main/java/jakarta/data/metamodel/constraint/InRecord.java
api/src/main/java/jakarta/data/metamodel/constraint/NotIn.java
api/src/main/java/jakarta/data/metamodel/constraint/NotInRecord.java
api/src/main/java/jakarta/data/metamodel/restrict/BasicRestriction.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java
api/src/test/java/jakarta/data/metamodel/restrict/BasicRestrictionRecordTest.java

I think that using `Set` here was okay when we only had literal values. But now that we also have `Expression`s, I think it should be a `List`. Otherwise we commit to always having well-defined equality for expressions, which I would not want to do. Also. the generated SQL would be (in principle) non-deterministic which is (in principle) a problem for prepared statement caching.
I've also added appropriate calls to `unmodifiableList()`.

sort out issues with in()

---

spec/src/main/asciidoc/jakarta-data.adoc
spec/src/main/asciidoc/method-query.asciidoc

After creating the Jakarta-Query project, I realized that we were not creating the spec with the proper theme, as shown by this warning:
```
[INFO] asciidoctor: ERROR: jakarta-data.adoc: could not locate or load the built-in pdf theme `../../theme/jakartaee-theme.yml' because of Errno::ENOENT No such file or directory - /Users/otaviosantana/Env/code/workspace-jakarta/theme/jakartaee-theme.yml; reverting to default theme
``` 
This PR fixes it, and now we have the proper Jakarta Theme on the spec.

Fix the URL reference at Jakarta EE theme on Data spec

---

api/src/main/java/jakarta/data/repository/CrudRepository.java

CrudRepository has a minor typo where the name of the entity class is the same as the name of the repository class used in that same example.

Fix typo in CrudRepository example entity

---

api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/metamodel/BasicAttribute.java
api/src/main/java/jakarta/data/metamodel/BasicAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/ComparableAttribute.java
api/src/main/java/jakarta/data/metamodel/ComparableAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/NavigableAttribute.java
api/src/main/java/jakarta/data/metamodel/NavigableAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/NumericAttribute.java
api/src/main/java/jakarta/data/metamodel/NumericAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/SortableAttribute.java
api/src/main/java/jakarta/data/metamodel/SortableAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/TemporalAttribute.java
api/src/main/java/jakarta/data/metamodel/TemporalAttributeRecord.java
api/src/main/java/jakarta/data/metamodel/TextAttributeRecord.java
api/src/test/java/jakarta/data/metamodel/ComparableExpressionTest.java

It's extremely useful to be able to reflect on the metamodel.
(Among other things, it lets you check correctness before doing an unchecked type cast.)

reify the attribute type

---

api/src/main/java/jakarta/data/expression/Expression.java
api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/restrict/Restriction.java
api/src/test/java/jakarta/data/metamodel/AttributeTest.java

Covers item 2 from #1086 - adding JavaDoc for the Expression class before proceeding to do likewise for the subtypes.

Javadoc for Expression

---

.github/dependabot.yml

Fixes #1095
Asciidoctor does not yet support jruby 10.  See error: 
```
Error:  Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:3.2.0:process-asciidoc (asciidoc-to-pdf) on project jakarta.data-tck-dist: Execution asciidoc-to-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:3.2.0:process-asciidoc failed: (ArgumentError) wrong number of arguments (given 3, expected 1..2): (LoadError) no such file to load -- asciidoctor-pdf -> [Help 1]
```

ignore: jruby 10.0.0.0

---

.github/workflows/ci.yml
.github/workflows/update.yml

My original PR passed using the Java 25-ea build of temurin here: 
https://github.com/jakartaee/data/actions/runs/14888194513/job/41813364483?pr=1094
Which correctly downloaded the JDK from the location: 
https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25%2B20-ea-beta/OpenJDK-jdk_x64_linux_hotspot_25_20-ea.tar.gz
After merging all subsequent builds have failed, like so: 
https://github.com/jakartaee/data/actions/runs/14909422899/job/41879770970
It looks like the setup-java step downloaded the `jmod` archive instead of the `jdk` from: 
https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25%2B21-ea-beta/OpenJDK-jmods_x64_linux_hotspot_25_21-ea.tar.gz
Which cannot be used by Maven to run a build.
I guess I was too quick.  Let's revert this until Java 25 …

fix: toolchain error java 25

---

api/src/main/java/jakarta/data/metamodel/package-info.java
api/src/main/java/module-info.java

This PR does the following:
- Include Restriction on our main Javadoc page that gives an overview of the key spec features.
- Promote Find/Delete with Constraints over Query by Method Name by moving the section on the former ahead of the section on the latter.
- Update the section on Find/Delete to be consistent with the ability to have parameters of the Restriction and Constraint.
I have also switched one of the example entity attributes used by these sections from an int year value to a temporal type to be able to show a broader set of patterns in the examples.

Module Javadoc should mention Restriction and prefer Constraints over Query by Method Name

---

api/src/main/java/jakarta/data/page/PageRequest.java

I noticed one place where we have a limitation against combining the `First` Query by Method Name keyword with `PageRequest`. We should state the same limitation for the `First` annotation.

Document same limitation for First annotation as for First keyword

---

api/src/main/java/jakarta/data/constraint/Like.java
api/src/main/java/jakarta/data/constraint/NotLike.java
api/src/main/java/jakarta/data/expression/NumericExpression.java
api/src/main/java/jakarta/data/expression/TextExpression.java
api/src/main/java/jakarta/data/expression/function/NumericOperatorExpression.java
api/src/main/java/jakarta/data/expression/literal/ComparableLiteral.java
api/src/main/java/jakarta/data/expression/literal/ComparableLiteralRecord.java
api/src/main/java/jakarta/data/expression/literal/Literal.java
api/src/main/java/jakarta/data/expression/literal/LiteralRecord.java
api/src/main/java/jakarta/data/expression/literal/NumericLiteral.java
api/src/main/java/jakarta/data/expression/literal/NumericLiteralRecord.java
api/src/main/java/jakarta/data/expression/literal/StringLiteral.java
api/src/main/java/jakarta/data/expression/literal/StringLiteralRecord.java
api/src/main/java/jakarta/data/expression/literal/TemporalLiteral.java
api/src/main/java/jakarta/data/expression/literal/TemporalLiteralRecord.java
api/src/test/java/jakarta/data/expression/ExpressionTest.java
api/src/test/java/jakarta/data/expression/TemporalExpressionTest.java
api/src/test/java/jakarta/data/expression/function/FunctionTest.java
api/src/test/java/jakarta/data/expression/literal/LiteralRecordTest.java
api/src/test/java/jakarta/data/expression/literal/LiteralToStringTest.java
api/src/test/java/jakarta/data/metamodel/TextAttributeTest.java
api/src/test/java/jakarta/data/restrict/RestrictTest.java
api/src/test/java/jakarta/data/restrict/TextRestrictionRecordTest.java

Two things:
1. Pull request #1114 was merged really quickly, and there were a couple of things missing from it.
2. Also, I think we should fix all `Literal`s to `Expression<Object, Whatever>`.

more on typing of literals

---

api/src/main/java/jakarta/data/metamodel/TemporalAttribute.java
api/src/main/java/jakarta/data/spi/expression/literal/ComparableLiteral.java
api/src/main/java/jakarta/data/spi/expression/literal/TemporalLiteral.java
api/src/main/java/jakarta/data/spi/expression/literal/TemporalLiteralRecord.java
api/src/main/java/module-info.java
api/src/test/java/jakarta/data/spi/expression/literal/LiteralToStringTest.java
spec/src/main/asciidoc/query-language.asciidoc

#1124 added java.time.Year (which we discussed on the Jakarta Data call and agreed on) to the list of temporal types.
This PR adds the rest of the support for it to the spec.

java.time.Year as a temporal attribute

---

api/src/main/java/jakarta/data/Limit.java
api/src/main/java/jakarta/data/page/CursoredPage.java
api/src/main/java/jakarta/data/page/PageRequest.java
api/src/main/java/jakarta/data/repository/By.java
api/src/main/java/jakarta/data/repository/Is.java
api/src/main/java/jakarta/data/repository/OrderBy.java
api/src/main/java/jakarta/data/repository/Repository.java
api/src/main/java/module-info.java

Here is what a solution to #857 might look like that enables comparisons other than equality for parameter based automatic query, making that pattern more complete and better able to match what Query by Method Name can do.  It is very concise and is all isolated to a single annotation in which the comparison types are specified by enum constants that read very naturally when used.
This allows us to switch basic code examples from Query by Method Name over to this more explicit pattern that does not seem like magic or require already having familiarity with query language.  I did so for several examples under this PR, although it might be best to view them in generated JavaDoc rather than source due to all of the escaping needed for `@`, `<`, `>` characters.
I didn't go through and …

other types of comparisons for parameter based automatic query

---

spec/src/main/asciidoc/repository.asciidoc

This pull request attempts to address problems introduced by #1140.
1. The new section about restrictions was added as a sub-subsection of "Null arguments to repository methods"
2. It was also in an unnatural  location with respect to the "natural" flow of topics
3. It smuggled in a requirement that the implementation throw `NullPointerException` for a null argument to a parameter of type `Restriction`, which was inconsistent with what we say about other special parameters
4. It also introduced a bunch of redundant, repetitive, and arguably *incorrect* statements about legal usage of `Restriction`
Folks, I'm sorry to have to be the bad guy again here. I had deliberately _not_ approved that pull request, and indeed I had explicitly asked that it not be merged.
@otaviojava 
- The Jakarta …

Clean up section on Restrictions

---

api/src/main/resources/rules.xml

When I tried to build the project locally, it failed with,
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.27.0:check (default) on project jakarta.data-api: PMD 7.14.0 has found 16 violations. For more details see: /Users/njr/lgit/data/api/target/pmd.xml -> [Help 1]
```
Here are the violations:
```
<file name="/Users/njr/lgit/data/api/src/main/java/jakarta/data/constraint/Constraint.java">
<violation beginline="22" endline="22" begincolumn="8" endcolumn="17" rule="ImplicitFunctionalInterface" ruleset="Best Practices" package="jakarta.data.constraint" class="Constraint" externalInfoUrl="https://docs.pmd-code.org/pmd-doc-7.14.0/pmd_rules_java_bestpractices.html#implicitfunctionalinterface" priority="2">
Annotate this interface with @FunctionalInterface or with …
```

Suppress PMD complaints about non-FunctionalInterfaces

---

stateful/pom.xml

The term `orm` was supposed to have been removed from the stateless module, but there are still a few occurrences remaining. This PR replaces them.

Replace missed occurrences of orm in Stateless module

---

api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/metamodel/BasicAttribute.java
api/src/main/java/jakarta/data/metamodel/TextAttribute.java
api/src/main/java/jakarta/data/metamodel/TextAttributeRecord.java
api/src/main/resources/jakarta/data/messages/Messages.properties

This PR started out as updating the default implementations of `attributeType()` and `declaringType()` to obtain the error message from the messages file.  But then I noticed that `Attribute.attributeType()` had a copy/paste error where it had a copy of the Javadoc from `declaringType()`.  Also `BasicAttribute.attributeType()` was overriding `Attribute.attributeType()` for no apparent reason and losing the Javadoc.  I removed the former to have it inherit the latter.  `TextAttribute` did not override `attributeType()`, but here it makes sense to because we can hard code a return value of `String.class` for text attribute and then not need to raise the UnsupportedOperationException for that method.  This last item is done as a separate commit in case anyone objects to just that part.

Attribute has wrong javadoc and should use message file for error

---

api/src/main/java/jakarta/data/metamodel/Attribute.java
api/src/main/java/jakarta/data/metamodel/BasicAttribute.java
api/src/main/java/jakarta/data/metamodel/SortableAttribute.java

It's confusing to say `BasicAttribute` is for entity attributes that are not comparable, because these attributes can be compared in some ways (equalTo, notEqualTo, isNull, isNotNull, in, notIn) which are allowed by Expression from which BasicAttribute inherits.
What we really meant here is to say they are not `java.lang.Comparable` in that they are not capable of order-based comparisons.  This PR clarifies.

Avoid confusion over the term comparable

---

.github/workflows/ci.yml
api/src/main/java/jakarta/data/repository/Select.java
api/src/main/java/module-info.java
pom.xml
stateful/src/main/java/jakarta/data/repository/stateful/Merge.java
tck-dist/pom.xml
tck/pom.xml

Related #1168 
Jenkins release build is catching javadoc errors when attempting to deploy that our current github actions build does not.
- add build step to github actions to catch errors put into javadoc during development
- fix errors that made it in while jenkins builds were broken. 
- skip javadoc for tck submodules (performance improvement and error prone)

fix: javadoc failures

---

pom.xml

Follow up to #1206
Related to #1168
I thought I could overwrite the `<distributionManagement>` config by blanking it out.
However, that behavior was not well documented, and to override nested elements we need to actually define `<repository>` and `<snapshotRepository>` elements. 
This is a work around until a snapshot of the new parent pom is released.  Tracked with issue: https://github.com/eclipse-ee4j/ee4j/issues/101

fix: distributionManagement override

---

api/src/main/java/jakarta/data/constraint/Constraint.java
api/src/main/java/jakarta/data/constraint/Like.java
api/src/main/java/jakarta/data/constraint/LikeRecord.java
api/src/main/java/jakarta/data/constraint/NotLike.java
api/src/main/java/jakarta/data/constraint/NotLikeRecord.java
api/src/test/java/jakarta/data/constraint/LikeTest.java
api/src/test/java/jakarta/data/restrict/TextRestrictionRecordTest.java

While trying out `Like` constraints, I noticed that the API method for supplying an already escaped pattern is buggy in how it translates the pattern because the implementation has no awareness of whether or not the pattern is already escaped.  This PR adds that awareness and corrects the implementation. It could have been alternatively corrected in a less verbose form, but this seemed clearer.  Let me know if anyone prefers the other form and I can switch it.
This also adds test cases, including trying out the example usage of the API that we had stated in Javadoc, which in some cases was also broken by the same issue.
This also adds some clarity to the Javadoc when the pattern supplied to an API method does not include escape characters. Previously this was unstated, risking that a user …

Pattern translation is broken when already-escaped pattern is supplied

---

api/src/main/java/jakarta/data/constraint/Constraint.java
api/src/main/java/jakarta/data/constraint/Like.java
api/src/main/java/jakarta/data/constraint/NotLike.java

Address review comment that was _originally posted by @gavinking in https://github.com/jakartaee/data/pull/1211#discussion_r2349969217_
> "no escape character is included" is very ambiguous to me. Does it mean:
> 
> - there is no escape character at all, or
> - there is no escape character explicitly specified, so the escape character defaults to `\`?

Clarify where patterns have no escape character
